### ISSUE TITLE
Parsing error when <defs> is after <use>

### ISSUE THREAD

**Issue by cubuspl42** [dnfield/flutter_svg#336] opened 2020-04-28 10:38 UTC
```
Bad state: Expected to find Drawable with id url(#_Image1).
Have ids: ()

When the exception was thrown, this was the stack: 
#0      DrawableDefinitionServer.getDrawable (package:flutter_svg/src/vector_drawable.dart:577:7)
#1      _Elements.use (package:flutter_svg/src/svg/parser_state.dart:184:34)
#2      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:776:26)
<asynchronous suspension>
#3      SvgParser.parse (package:flutter_svg/parser.dart:14:60)
...
```

When my SVG file has `<defs><image id="_Image1"  ... /></defs>` after `<use xlink:href="#_Image1" ... />` (i.e. later in the XML file), `flutter_svg` fails to load it.

[test.svg.zip](https://github.com/dnfield/flutter_svg/files/4545116/test.svg.zip)

**Comment by dnfield** [comment] 2020-04-28 13:06
Duplicate of #102

**Closed by dnfield** 2020-04-28 13:06 UTC
