### ISSUE TITLE
Widgets next to SvgPicture.asset disappearing

### ISSUE THREAD

**Issue by jakubjaniec** [dnfield/flutter_svg#961] opened 2023-07-07 15:43 UTC
I've encountered a weird behaviour after upgrading my app to Flutter 3.10. 

<table> 
<tr>
<th>Expected (Flutter 3.7.12)</th>
<th>Actual (Flutter 3.10.5)</th>
</tr>
<td><img src="https://github.com/dnfield/flutter_svg/assets/52073833/8ca0dc64-85bb-475d-99bd-891aecb0d81b" width=250></td>
<td><img src="https://github.com/dnfield/flutter_svg/assets/52073833/05dcc89a-9084-4afb-8337-132a70429e12" width=250></td>

</table>

The code below causes content in Column to disappear. In Flutter version 3.7.12 it's working properly.

```
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(backgroundColor: Theme.of(context).colorScheme.inversePrimary),
        body: ListView.separated(
          itemCount: 2,
          padding: const EdgeInsets.all(16),
          itemBuilder: (context, index) => Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              SvgPicture.asset('assets/images/test.svg'),
              const SizedBox(width: 8),
              const Column(
                children: [
                  Text('testing'),
                  SizedBox(height: 8),
                  Text('testing'),
                ],
              ),
            ],
          ),
          separatorBuilder: (_, __) => const SizedBox(height: 16),
        ),
      );
``` 

I've found 2 workarounds for that. The first one is to set Row's `crossAxisAlignment` to other than `start` and `stretch`. The second one is to pass `width` to `SvgPicture.asset` with value other than from the source .svg file. This also works for `height`.

The svg file I was using for that example:

```
<svg width="24" height="24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M20 18.22A1.78 1.78 0 0 1 18.22 20H5.78A1.78 1.78 0 0 1 4 18.22V5.78A1.78 1.78 0 0 1 5.78 4H18a2 2 0 0 1 2 2v12.22Z" fill="#00AB44" stroke="#00AB44" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="m8 12 2.7 3L17 8" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
</svg>

```

**Comment by dnfield** [comment] 2023-07-07 15:48
This is related to a bug in impeller that was fixed yesterday. It will probably not get cherry picked into 3.10 at this point, but I'll file a CP request for the next beta since I think I missed the cut on that.

In the mean time I have an idea for a work around I can test.

**Comment by dnfield** [comment] 2023-07-07 15:56
The work around does not work :( I will file a stable cherry pick as well for 3.10 but it may not be accepted.

**Comment by dnfield** [comment] 2023-07-07 15:56
Duplicate of #942

**Comment by dnfield** [comment] 2023-07-07 15:56
(One possible work around is --no-enable-impeller)

**Closed by dnfield** 2023-07-07 15:56 UTC

**Comment by Greismorr** [comment] 2023-07-10 17:55
--no-enable-impeller resolved the issue for me. To disable it when deploying the app add the tag:

```
  <key>FLTEnableImpeller</key>
  <false />
```

 Under the top-level <dict> in your app’s Info.plist file. The full doc is [here](https://docs.flutter.dev/perf/impeller)

**Comment by dnfield** [comment] 2023-07-10 18:10
I am requesting a cherry pick of the impeller fix for this into the 3.10 stable.

**Comment by TrongBa** [comment] 2023-12-15 04:21
I am facing same issue:
`Opacity(
            opacity: 1,
            child: Row(
              children: [
                SvgPicture.asset(
                  AppSVGs.iconAccountInfor,
                  width: 24,
                  height: 24,
                ),
                Expanded(
                  child: Text(
                    title,
                    style: TextStyles.lightTextStyle(
                        color: AppColor.black151515,
                        size: 18,
                        fontFamily: NameFont.hiragino),
                  ),
                ),
              ],
            ),
          ),`
Only on device iPhone 12 mini, The text isn't displayed. ( Other device work).
In case:
- Change the width or height of svg different 24. It work

**Comment by TrongBa** [comment] 2023-12-15 04:25
@dnfield please check

**Comment by dnfield** [comment] 2023-12-15 04:36
Please file a minimally complete reproduction of this, and check whether it happens on the latest stable/beta channels.
