### ISSUE TITLE
Showing invalid renders

### ISSUE THREAD

**Issue by omzer** [dnfield/flutter_svg#1023] opened 2024-01-04 14:09 UTC
**Consider the following images:**
| Image link | Expected (opened link on chrome) | Actual (flutter - grey background for better visiblity) |
|---|---|---|
| [Link](https://static-content.webcargonet.com/airlines_logos_matrix/EK/logo_small.svg) | ![image](https://github.com/dnfield/flutter_svg/assets/23129313/65573500-934c-4b58-9ac7-5be40206e191) | ![image](https://github.com/dnfield/flutter_svg/assets/23129313/961bc90c-2853-41c6-ada5-f6415c291343) |
| [Link](https://static-content.webcargonet.com/airlines_logos_matrix/90/logo_small.svg) | ![image](https://github.com/dnfield/flutter_svg/assets/23129313/1ce8ace1-3707-4e67-919b-01cf16b29ab4) | ![image](https://github.com/dnfield/flutter_svg/assets/23129313/f958e0c8-1c91-4b48-af23-5e08f20e027e) |

**Code:**
```
Container(
  height: 110,
  color: Colors.grey,
  width: double.infinity,
  child: SvgPicture.network(url),
);
```

What can be the issue?

**Comment by dnfield** [comment] 2024-01-04 15:03
Please share the SVG

**Comment by omzer** [comment] 2024-01-04 21:42
@dnfield You can find the SVGs used in the first column (Image link).
The grey color is just to show that the component renders blank, posting a blank white image might not be very clear.

**Comment by dnfield** [comment] 2024-01-04 22:15
I see, sorry about that.

This is a duplicate of #820

**Comment by dnfield** [comment] 2024-01-04 22:15
Also, for what it's worth, your SVG eamples are basically giant base64 encoded images that are then centered and clipped - it would be _much_ better to include them as image assets and do that clipping yourself.

**Closed by dnfield** 2024-01-04 22:15 UTC

**Comment by omzer** [comment] 2024-01-04 22:22
Unfortunately I'm limited to use the network URL, as these URLs come from the backend dynamically and new airlines (urls) can be added every often.

So the suggestion on the mentioned ticket (placing <defs/> on top) won't work, nor adding it as an asset.

**Comment by dnfield** [comment] 2024-01-04 23:09
Yes, unfortunately rendering this particular type of SVG isn't supported by the package right now, and supporting it correctly is not super hard but also not super easy. I don't have plans to get to it anytime soon though. Sorry.

**Comment by omzer** [comment] 2024-01-04 23:11
Can you describe what are the required changes to do the fix? I might be able to open a PR
