### ISSUE TITLE
flutter_svg/src/cache.dart': Failed assertion: line 104 pos 14: '_cache.length < maximumSize': is not true

### ISSUE THREAD

**Issue by rydmike** [dnfield/flutter_svg#877] opened 2023-03-08 20:41 UTC
When using package version **flutter_svg 2.0.2** I get this assertion on its cache handling:

```console
package:flutter_svg/src/cache.dart': Failed assertion: line 104 pos 14: '_cache.length < maximumSize': is not true.

The relevant error-causing widget was: 
  SvgPicture SvgPicture:file:///Users/rydmike/dev/code/flex_color_scheme/example/lib/shared/widgets/universal/svg_asset_image.dart:51:23
When the exception was thrown, this was the stack: 
#2      Cache._add (package:flutter_svg/src/cache.dart:104:14)
#3      Cache.putIfAbsent (package:flutter_svg/src/cache.dart:95:7)
#4      SvgLoader.loadBytes (package:flutter_svg/src/loaders.dart:144:22)
#5      _VectorGraphicWidgetState._loadPicture (package:vector_graphics/src/vector_graphics.dart:329:16)
#6      _VectorGraphicWidgetState._loadAssetBytes (package:vector_graphics/src/vector_graphics.dart:363:5)
#7      _VectorGraphicWidgetState.didChangeDependencies (package:vector_graphics/src/vector_graphics.dart:293:5)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5133:11)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4958:5)
...     Normal element mounting (10 frames)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3964:16)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3695:20)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5007:16)
#22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5147:11)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:4701:7)
#24     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2773:19)
#25     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:865:21)
#26     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1286:15)

```

If I switch to version **flutter_svg 1.1.6** everything runs fine.

In this use case I actually "only" have **42 source SVGs**, but dynamically create new versions by replacing a color value in the source SVGs files, with quasi random new color values. So from the view point of `flutter_svg` the SVGs file is new, so it will go past the default max cache 100 size. There are in fact probably over 1000 different versions created via a builder dynamically.

I'm using `SvgPicture.string` to construct the new SVG files. I load the original SVG file as a string asset using `rootBundle.loadString`, in order to be able to replace a known color string value in the source files, with a new color value, before passing it to `SvgPicture.string`. It has worked well for the use case in 1.x.x versions.

> **Sidenote:** I also tried using raw `SvgPicture` with `SvgAssetLoader` and `colorMapper`, but I could not get it to work correctly regarding changing just the desired color. I probably was not using it correctly.

Regarding, using `SvgPicture.string`, I also tried adding a `ValueKey<String>` to it, made up of the asset name and the new color, as that is unique for the SVGs created dynamically too. First thought it could help with re-use of some of them in the cache, but later looked at the code for it, and saw that nope that is not it.

I looked cache code, plus som other things and tried some fixes. Initially I thought I found it, and was going to submit a PR, but later realized, my initial assumption was not correct.

At this point I don't have simple reproduction sample. If needed, I guess I can extract one from the code base where this happens. It could serve as a minimal case to reproduce this issue, unless it is something that is simple to solve, or maybe I'm just using the new version wrong.

**BUT** as mentioned, if I use **flutter_svg 1.1.6**, I don't see this issue. So for now I'm sticking to it for this use case.

**Comment by dnfield** [comment] 2023-03-08 21:32
Duplicate of #863

**Closed by dnfield** 2023-03-08 21:32 UTC

**Comment by rydmike** [comment] 2023-03-08 23:55
Ok, thx @dnfield and good to know that it is a known issue. Had a look at the findings in it, and it seems I was on the right track as well to where the issue is.

Is there a fix planned?

**Comment by dnfield** [comment] 2023-03-09 00:29
The fix is not complicated but I have not hd time to look at it. I'd be open to a PR
