### ISSUE TITLE
build --web-renderer html not show svg resource 

### ISSUE THREAD

**Issue by dansunhappy** [dnfield/flutter_svg#776] opened 2022-09-21 09:12 UTC
`flutter_svg: ^1.1.5`

`Flutter 3.0.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cd41fdd495 (4 months ago) • 2022-06-08 09:52:13 -0700
Engine • revision f15f824b57
Tools • Dart 2.17.3 • DevTools 2.12.2`

**svg resource**

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="502.693" height="717.385"><symbol id="dF"><path d="M.107.405.1.162.096.05C.092.016.076 0 .048 0 .016 0 0 .017 0 .05c0 .04.002.098.005.177.004.08.006.138.006.178 0 .051 0 .11.002.176l.003.177c0 .032.016.049.047.049.033 0 .049-.017.049-.05L.109.582A7.244 7.244 0 0 1 .107.405z"/></symbol><use xlink:href="#dF" transform="matrix(20 0 0 -20 372.546 64.142)" fill="#231f20"/><use xlink:href="#dF" transform="matrix(20 0 0 -20 378.026 64.142)" fill="#231f20"/></svg>`

**build --web-renderer html && code**

```
Row(
        children: [
          Container(
            width: 400,
            height: 400,
            color: Colors.yellow.withOpacity(0.2),
            child: SvgPicture.asset('assets/test.svg'),
          ),
          Container(
            width: 10,
          ),
          Container(
            color: Colors.yellow.withOpacity(0.2),
            width: 400,
            height: 400,
            child: SvgPicture.asset(
              'assets/test.svg',
              color: Colors.red,
            ),
          )
        ],
      )

```
**not show svg resource**

<img width="1194" alt="截屏2022-09-21 17 08 30" src="https://user-images.githubusercontent.com/12166990/191464782-d12f184b-e170-4e17-bcfe-62cdad5a5124.png">

**Comment by dnfield** [comment] 2022-09-21 16:32
I am able to render this SVG using the HTML backend - closing because I'm unable to reproduce.

**Closed by dnfield** 2022-09-21 16:32 UTC

**Comment by dansunhappy** [comment] 2022-09-22 02:20
set color: Colors.red, not show

**Comment by dansunhappy** [comment] 2022-09-22 02:25
[svg_bug.zip](https://github.com/dnfield/flutter_svg/files/9621696/svg_bug.zip)
reproduce code

**Comment by dnfield** [comment] 2022-09-22 02:31
Ahh yeah that's a known bug in the html renderer

**Comment by dansunhappy** [comment] 2022-09-22 08:05
```
ColorFiltered(
                colorFilter: ColorFilter.mode(Colors.blue, BlendMode.srcIn),
                child: RawPicture(pictureInfo),
              )
```
is not show ,but use 
```
ColorFiltered(
              colorFilter: ColorFilter.mode(Colors.blue, BlendMode.srcIn),
              child: RawImage(
                image: image,
              ),
            )
```
it work, i don't know why

**Comment by dnfield** [comment] 2022-09-22 14:24
We probably do something special for images. Pictures are harder.
