### ISSUE TITLE
color property does not work

### ISSUE THREAD

**Issue by BigGitWorld** [dnfield/flutter_svg#391] opened 2020-08-04 10:50 UTC
I'm going to change color of svg icon (set tint color like as **colorFilter** in android), so I used ``color`` property.
But it does not change the color.

I'm using svg icons from online sites, such as below ( a shopping_basket icon): 
```
<?xml version="1.0" encoding="iso-8859-1"?>
<svg xmlns="http://www.w3.org/2000/svg"
	 version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 511.865 511.865" style="enable-background:new 0 0 511.865 511.865;" xml:space="preserve" width="512" height="512">
<g>
	<path d="M179.415,341.464l159.047-20.81c31.348-4.102,59.99-19.325,80.651-42.865   c20.661-23.541,32.04-53.916,32.04-85.53v-15.847c0-7.447-5.464-13.768-12.834-14.843L91.046,110.895L51.812,82.433   c-6.709-4.857-16.088-3.357-20.947,3.352c-4.858,6.71-3.358,16.089,3.352,20.947l38.737,28.102l77.408,190.557   c-2.585,2.957-4.806,6.309-6.566,10.036c-6.294,13.325-5.411,28.128,2.425,40.611c8.029,12.792,21.34,20.128,36.519,20.128h235.06   c8.284,0,15-6.716,15-15s-6.716-15-15-15h-235.06c-4.773,0-8.614-2.102-11.11-6.077c-2.387-3.803-2.625-7.79-0.708-11.849   C172.674,344.528,175.536,342.265,179.415,341.464z M421.152,189.382v2.877c0,46.074-30.2,84.583-73.479,96.059l-10.705-61.538   c-0.072-1.061-0.254-2.093-0.536-3.084l-8.331-47.892L421.152,189.382z M318.05,293.07l-63.023,8.246l-17.63-60.85l71.85,1.999   L318.05,293.07z M296.858,171.245l7.143,41.063l-75.37-2.097l-14.8-51.081L296.858,171.245z M108.989,143.83l72.229,10.54   l15.925,54.964l-62.249-1.732L108.989,143.83z M205.91,239.59l19.025,65.663l-47.127,6.166c-0.239,0.013-0.478,0.031-0.719,0.055   l-29.864-73.517L205.91,239.59z"/>
	<circle cx="203.622" cy="442.052" r="32.88"/>
	<circle cx="381.549" cy="442.052" r="32.88"/>
	<circle cx="29.813" cy="83.785" r="29.813"/>
	<circle cx="203.622" cy="442.052" r="11.755"/>
	<circle cx="381.549" cy="442.052" r="11.755"/>
</g>
</svg>

```
A sample usage:
```
IconButton(
  icon: SvgPicture.asset("assets/icons/shopping_basket.svg", color: Colors.red,),
  onPressed: () {},
),
```
what is the problem? How do I have to change color of a svg icon?

**Comment by dnfield** [comment] 2020-08-06 04:10
I am not able to reproduce this. The SVG shows up as red for me with your code.

**Comment by BigGitWorld** [comment] 2020-08-06 08:06
Its strange! So why the color in this code does not work for me? I'm using Intellij IDEA.

**Comment by dnfield** [comment] 2020-08-06 14:16
IDE shouldn't matter.  Are you k. The latest versions of flutter and flutter_svg?

Can you share a complete minimal reproduction?

**Comment by BigGitWorld** [comment] 2020-08-09 06:31
I'm using the flutter_svg version 0.17.4
because my flutter sdk version (1.17.5) does not allow me to install the flutter_svg 0.18.0.
```
The current Flutter SDK version is 1.17.5.

Because flutter_app_1 depends on flutter_svg >=0.18.0 which requires Flutter SDK version >=1.18.0-6.0.pre <2.0.0, version solving failed.

=pub get failed (1; Because flutter_app_1 depends on flutter_svg >=0.18.0 which requires Flutter SDK version >=1.18.0-6.0.pre <2.0.0, version solving failed.)
```

**Comment by BigGitWorld** [comment] 2020-08-09 07:32
> IDE shouldn't matter. Are you k. The latest versions of flutter and flutter_svg?

I'm using the latest versions:
flutter_svg version: 0.18.0
flutter sdk version: 1.20.1

> Can you share a complete minimal reproduction?

Its a simple empty flutter project with a ``Container`` widget a ``SvgPicture.asset("assets/icons/shopping_basket.svg", color: Colors.red,)`` child inside it.

- The above svg code is inside of ``assets/icons/shopping_basket.svg``
- I added ``flutter_svg: ^0.18.0`` to the ``dependencies`` section of ``pubspec.yaml``.

**Comment by BigGitWorld** [comment] 2020-08-09 08:59
Do I have to declare any special command (such as color, style, fill) in the SVG file?

**Comment by dnfield** [comment] 2020-08-09 14:45
You shouldn't. I used the svg you pasted in above and was able to make it red

**Comment by dnfield** [comment] 2020-08-14 02:05
I'm going to close this as not reproducible. Please feel free to comment if you have a full reproducible project I can try.

**Closed by dnfield** 2020-08-14 02:05 UTC
