### ISSUE TITLE
crash on iOS when svg in list 

### ISSUE THREAD

**Issue by mustafa-707** [dnfield/flutter_svg#1078] opened 2024-06-11 21:38 UTC
Hello ,

I'm facing this issue is cause a crash on iOS when i try to show my svgs in list , column , row or wrap widget 

for example : 
```
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

const urls = [
  'https://ik.imagekit.io/mashkor/general/general_pickup_en.svg',
  'https://ik.imagekit.io/mashkor/general/general_summer_en.svg',
  "https://ik.imagekit.io/mashkor/general/newsfeeds_powder_en.svg"
];

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Wrap(
          children: List.generate(
            urls.length,
            (index) => SvgPicture.network(
              urls[index],
              fit: BoxFit.cover,
            ),
          ),
        ),
      ),
    );
  }
}


```

its only when using flutter 3.22.1 and above 

tested on iOS 17.4 and 17.5 simulator and real devices 

is  our Svgs is bad or is caused from flutter_svg 

Thank you

**Comment by kamranbekirovyz** [comment] 2024-06-12 16:56
Same here. This code block started causing crash on iOS Simulator on Flutter v3.22..1: <img width="499" alt="Screenshot 2024-06-12 at 20 55 22" src="https://github.com/dnfield/flutter_svg/assets/59581562/5bf6d7bb-ee18-4ed1-9b03-c25315f4f6a4">

**Comment by reinhardt-s** [comment] 2024-06-12 21:49
I experienced the same behaviour. 
It seems to happen only with specific svg files. Some 17 of 18 are loading just fine but one specific image let's the app crash.
XML is valid.

```dart
Stack(
    children: [
        Positioned(
          bottom: 20,
          left: 0,
          child: SvgPicture.asset(
             _progressController.getSVGToLesson(lessonNumber: lessonNumber),
          ),
       ),
    ]
)
```

I can provide a minimum SVG that will break.
The culprit is the path in group 1395

```xml
<svg xmlns="http://www.w3.org/2000/svg" width="86" height="86" viewBox="0 0 86 86">
  <g id="Group_4246" data-name="Group 4246" transform="translate(-250 -313)">
    <g id="Group_1102" data-name="Group 1102" transform="translate(2 -8)">
    </g>
    <g id="layer1" transform="translate(151.834 -6.666)">
      <g id="Group_1399" data-name="Group 1399" transform="translate(131.192 342.263)">

        <!-- This group breaks it -->
        <g id="Group_1395" data-name="Group 1395" transform="translate(0.342 11.324)">
          <path id="Path_2556" data-name="Path 2556" d="M217.547,583.222h0Zm-1.348,3.909a.044.044,0,0,0,.035-.023h0c.013-.024.06-.121.112-.233h0a2.673,2.673,0,0,1,.55-.8h0a3.188,3.188,0,0,1,1.142-.711h0a.548.548,0,0,0,.261-.18h0a1.224,1.224,0,0,0,.313-.907h0a1.152,1.152,0,0,0-.3-.731h0a1.01,1.01,0,0,0-.7-.318h-.022c.01-.013.023-.029.037-.045h0a1.567,1.567,0,0,0,.251-.473h0a.966.966,0,0,0-.112-.758,1.623,1.623,0,0,0-.79-.586h0a1.95,1.95,0,0,0-.7-.137,2.66,2.66,0,0,0-.653.095h0a2.684,2.684,0,0,1-.661.094,1.7,1.7,0,0,1-.263-.02h0a2.062,2.062,0,0,1-.663-.206h0l-.192-.091a.036.036,0,0,0-.043.009l-.053.061h0a2.039,2.039,0,0,0-.276.52h0a1.932,1.932,0,0,0,.509,1.956h0a1.931,1.931,0,0,0,1.268.619h0c.051,0,.1.007.128.01h0l-.045.059h0a2.173,2.173,0,0,0-.416.917,2.225,2.225,0,0,0,.011.848h0a1.356,1.356,0,0,0,1.143,1.007h0l.122.022Z" transform="translate(-213.383 -581.097)"/>
        </g>
      </g>
      
      <g id="Group_1404" data-name="Group 1404" transform="translate(125.59 337.066)">

      </g>
    </g>
  </g>
</svg>
```

```bash
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (7 days ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3
```

Tested on iOS 17.2, 17.5 iPhone 15, iPhone 15 Pro Max

**Comment by DevanshiGor** [comment] 2024-06-14 11:42
I am facing same issue Regardless of any specific svgImage.

**Comment by anchao-lu** [comment] 2024-06-17 02:27
same for one specific svgimage
```xml
<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg t="1689828614673" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="2151" xmlns:xlink="http://www.w3.org/1999/xlink" width="90" height="90"><path d="M361.472 120.32zM120.32 361.472h241.152V120.32H120.32zM361.472 0zM0 0h481.792v481.792H0z m1024 542.208v120.32h-120.32v-120.32z m-241.152 361.472h-120.32v-241.152h120.32z m0 0h120.832v-120.832H1024V1024h-241.152z m-481.792-60.416H180.736v-120.32h120.32zM903.68 120.32z m-241.152 0v241.152h241.152V120.32z m-301.056 421.888zM481.792 1024H0v-481.792h481.792zM301.056 301.056H180.736V180.736h120.32zM1024 0z m0 0v481.792h-481.792V0z m-361.472 903.68V1024h-120.32v-120.32z m60.416-602.624V180.736h120.32v120.32z m-361.472 361.472z m-241.152 0v241.152h241.152v-241.152z m542.208-120.32v120.32h-120.32v-120.32z" fill="#B2B2B2" p-id="2152"></path></svg>
```

**Comment by jonahwilliams** [comment] 2024-06-17 18:31
Duplicate of https://github.com/flutter/flutter/issues/149309

You all really need to file flutter bugs in the flutter repo

**Closed by jonahwilliams** 2024-06-17 18:31 UTC
