### ISSUE TITLE
Gradient not rendering

### ISSUE THREAD

**Issue by lukepighetti** [dnfield/flutter_svg#521] opened 2021-03-18 17:09 UTC
### Version

`flutter_svg: 0.20.0-nullsafety.3`
exported from `Figma Desktop App version 95.8`

### Implementation

```dart
SvgPicture.asset(
  'assets/icon.svg',
),
```

### Raw SVG

```xml
<svg width="24" height="30" viewBox="0 0 24 30" fill="none" xmlns="http://www.w3.org/2000/svg">
<mask id="mask0" mask-type="alpha" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="30">
<path fill-rule="evenodd" clip-rule="evenodd" d="M8.08327 0C6.66239 3.06447 8.71414 5.16239 8.51046 9.1976C7.99702 7.64048 6.82436 6.56225 5.8821 6.20172C6.85756 12.2102 1.17851 13.7477 0.177535 19.2258C-0.697505 24.0164 1.60368 28.2704 8.38372 29.9245C6.70774 28.3741 6.18174 26.4359 6.53241 24.4459C7.29326 20.1221 11.8284 18.6441 12.7496 14.5745C12.7569 14.5411 12.763 14.508 12.7699 14.4746C15.1901 16.657 16.4826 21.3564 14.1381 24.7563C15.3294 24.4468 16.3073 23.8796 17.0977 23.1473C17.4038 24.9211 17.45 27.6898 15.1512 29.9245C24.6463 27.8312 23.8579 18.5671 22.0564 16.2801C21.8802 17.555 21.0072 19.2744 19.0344 20.2815C19.9516 18.0405 20.0277 15.4386 19.5147 13.4997C17.2402 4.90977 9.33448 5.06452 8.08327 0Z" fill="white"/>
</mask>
<g mask="url(#mask0)">
<path fill-rule="evenodd" clip-rule="evenodd" d="M8.08327 0C6.66239 3.06447 8.71414 5.16239 8.51046 9.1976C7.99702 7.64048 6.82436 6.56225 5.8821 6.20172C6.85756 12.2102 1.17851 13.7477 0.177535 19.2258C-0.697505 24.0164 1.60368 28.2704 8.38372 29.9245C6.70774 28.3741 6.18174 26.4359 6.53241 24.4459C7.29326 20.1221 11.8284 18.6441 12.7496 14.5745C12.7569 14.5411 12.763 14.508 12.7699 14.4746C15.1901 16.657 16.4826 21.3564 14.1381 24.7563C15.3294 24.4468 16.3073 23.8796 17.0977 23.1473C17.4038 24.9211 17.45 27.6898 15.1512 29.9245C24.6463 27.8312 23.8579 18.5671 22.0564 16.2801C21.8802 17.555 21.0072 19.2744 19.0344 20.2815C19.9516 18.0405 20.0277 15.4386 19.5147 13.4997C17.2402 4.90977 9.33448 5.06452 8.08327 0Z" fill="url(#paint0_linear)"/>
</g>
<defs>
<linearGradient id="paint0_linear" x1="23.8097" y1="30.4672" x2="23.8097" y2="-1.08725" gradientUnits="userSpaceOnUse">
<stop stop-color="#F05236"/>
<stop offset="1" stop-color="#F5803B"/>
</linearGradient>
</defs>
</svg>
```

### Actual
<img width="46" alt="Screen Shot 2021-03-18 at 1 08 12 PM" src="https://user-images.githubusercontent.com/666539/111667356-01ab4d00-87eb-11eb-900e-822318896c98.png">

### Expected

<img width="104" alt="Screen Shot 2021-03-18 at 1 09 41 PM" src="https://user-images.githubusercontent.com/666539/111667555-34eddc00-87eb-11eb-9df3-6345385c6edc.png">

**Comment by dnfield** [comment] 2021-03-24 00:57
Does it work if you move the defs up.?  If so dupe of #102

**Comment by zixuan-espressoft** [comment] 2021-03-25 10:15
Move the <defs>...</def> up below <svg> works for me.

**Closed** 2021-03-25 17:35 UTC
