### ISSUE TITLE
Latest version of flutter_svg not picking images from cache which cached using precachePicture

### ISSUE THREAD

**Issue by chetansharmapsi** [dnfield/flutter_svg#667] opened 2022-02-17 11:11 UTC
Latest version of `flutter_svg: ^1.0.3` not picking cached network images. It is working till `flutter_svg: ^0.21.0+1` but not in latest version of `flutter_svg` library.

I am caching SVG images using below code :

```
 var svgPicture = SvgPicture.network(
        imageUrl,
        fit: imageFit,
        width: width,
        height: height,
      );
      precachePicture(
        svgPicture.pictureProvider,
        Get.context!,
      );
```

And trying to show using below  code : 
```
SvgPicture.network((imageURL ?? ''),
                    fit: imageFit,
                    width: width,
                    height: height,
                    placeholderBuilder: (BuildContext context) => PlaceholderImageWidget(
                          fit: imageFit,
                          height: height,
                        ),
                    cacheColorFilter: true)
```

Above code is working with `flutter_svg: ^0.21.0+1`  but not with `flutter_svg: ^1.0.3` .

I also tried to cache images using below code :

```
 precachePicture(
        NetworkPicture(SvgPicture.svgByteDecoderBuilder, imageUrl),
        null,
      );
```

But that also not working with `flutter_svg: ^1.0.3`.

So please guide me if there is any other recommended way to pre cache SVG images which is supported with latest version of `flutter_svg`.

**Comment by chetansharmapsi** [comment] 2022-02-17 11:47
I checked changelogs, It seems some change was introduced in version 0.22.0 related caching
[](https://pub.dev/packages/flutter_svg/changelog#0220)0.22.0 
`Expose PictureCache on PictureProvider, and deprecate PictureProvider.cacheCount and PictureProvider.clearCache. This is intended to allow users to set a maximum cache size, which was previously impossible.`

**Comment by chetansharmapsi** [comment] 2022-02-18 05:34
HI @dnfield  thanks for reply, I am using exact code mentioned below : 

I am caching SVG images using below code :

```
 var svgPicture = SvgPicture.network(
        imageUrl,
        fit: imageFit,
        width: width,
        height: height,
      );
      precachePicture(
        svgPicture.pictureProvider,
        Get.context!,
      );
```
And trying to show using below code :

```
SvgPicture.network((imageURL ?? ''),
                    fit: imageFit,
                    width: width,
                    height: height,
                    placeholderBuilder: (BuildContext context) => PlaceholderImageWidget(
                          fit: imageFit,
                          height: height,
                        ),
                    cacheColorFilter: true)
```
Above code is working with flutter_svg: ^0.21.0+1 but not with flutter_svg: ^1.0.3 .

I also tried to cache images using below code :

```
 precachePicture(
        NetworkPicture(SvgPicture.svgByteDecoderBuilder, imageUrl),
        null,
      );
```
But that also not working with flutter_svg: ^1.0.3.

I also tried with same  fit, width and height, but same issue.

Do we need to provide cache count explicitly, from version 0.22.0? Please confirm. If this is missing and need to provide cache count, please guide me how we can do that.

**Comment by dnfield** [comment] 2022-02-18 07:23
The specific svg can make a difference.  As well as surrounding application code where it's used.

**Comment by dnfield** [comment] 2022-02-18 18:49
The surrounding application code does have an impact, because of changes to the way the cache is handled now - if your SVGs have `em` units in them and the default text style has changed, for example, they won't get cached. See https://github.com/dnfield/flutter_svg/issues/642

**Comment by dnfield** [comment] 2022-03-01 06:12
I'm going to close this since I don't have a complete reproduction to work from. Will re-open if one is provided.

**Closed by dnfield** 2022-03-01 06:12 UTC
