### ISSUE TITLE
SVG not rendered

### ISSUE THREAD

**Issue by ened** [dnfield/flutter_svg#65] opened 2018-09-20 22:51 UTC
This SVG, although processed with svgcleaner will cause the following warning in the console:

```
I/flutter (29709): unhandled element circle; Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#ec500(), name: "assets/icons/menu-favourites.svg", colorFilter: null)
I/flutter (29709): unhandled element filter; Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#ec500(), name: "assets/icons/menu-favourites.svg", colorFilter: null)
I/flutter (29709): unhandled element use; Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#ec500(), name: "assets/icons/menu-favourites.svg", colorFilter: null)
```

The SVG will not render the circle.

[menu-favourites.svg.zip](https://github.com/dnfield/flutter_svg/files/2403324/menu-favourites.svg.zip)

**Comment by dnfield** [comment] 2018-09-22 18:16
Filters aren't supported yet, neither are referenced shapes

**Comment by dnfield** [comment] 2018-09-26 22:08
Duplicate of #53

**Closed by dnfield** 2018-09-26 22:08 UTC
