### ISSUE TITLE
Colors in SVG files are not rendered correctly.

### ISSUE THREAD

**Issue by caokietbk** [dnfield/flutter_svg#707] opened 2022-05-14 02:52 UTC
Hi,

I have a problem when using this library to render SVG files. (It doesn't render here the way it does in Chrome).
Here is the svg file.
![svg_file](https://user-images.githubusercontent.com/45527841/168408072-6baac833-21fb-4e71-be2e-5bf746ca5ee2.svg)

And here is what it rendered with the flutter_svg package.
![image](https://user-images.githubusercontent.com/45527841/168408080-a16ae515-d63f-4d92-98ce-ab34c98440da.png)

I'm looking forward to hearing from you soon.
Thank you very much.

**Comment by ivofernandes** [comment] 2022-05-16 10:37
Are you using gradients? I had some problems with colors in gradients for example with the facebook or instagram svg logo

**Comment by caokietbk** [comment] 2022-05-16 11:22
> Are you using gradients? I had some problems with colors in gradients for example with the facebook or instagram svg logo

I think my issue is the same as issue: #53 

You can check your svg file with this method.
I hope it helps.

<img width="839" alt="image" src="https://user-images.githubusercontent.com/45527841/168581626-693f33ac-3164-4fdf-a3dd-ffd9267d8df1.png">

**Comment by dnfield** [comment] 2022-05-16 15:47
Closing as duplicate of #53

**Closed by dnfield** 2022-05-16 15:48 UTC
