### ISSUE TITLE
SvgPicture not working

### ISSUE THREAD

**Issue by alex9153** [dnfield/flutter_svg#531] opened 2021-04-08 13:14 UTC
Shows one white color

[71b8913e-e277-4739-8ac2-3d9059279a46.svg.zip](https://github.com/dnfield/flutter_svg/files/6278897/71b8913e-e277-4739-8ac2-3d9059279a46.svg.zip)

**Comment by dnfield** [comment] 2021-04-08 16:04
Duplicate of #102

**Closed by dnfield** 2021-04-08 16:04 UTC
