### ISSUE TITLE
Other widget are disappearing while using in iOS and Flutter 3.10

### ISSUE THREAD

**Issue by burekas7** [dnfield/flutter_svg#942] opened 2023-06-14 09:43 UTC
Since updating Flutter to 3.10.4, using flutter_svg with iOS makes other widget to disappear.
In Android it doesn't happen.
I updated to the last version 2.0.7, but it still doesn't help.
And there is no errors in the logs :/

**Comment by burekas7** [comment] 2023-06-14 09:58
Ok, I found that when the property "width?" is null (As it was before), this what makes the problem in iOS with Flutter 3.10.4.
When I put a value there the problem is fixed.

Why is that, what have been changed?

**Comment by burekas7** [comment] 2023-06-14 10:04
Ok I found that when I set "width" property above a specific value, that is what makes the problem in iOS with Flutter 3.10.4.
All the times it was null by the way, but why there is a problem with the width values?

**Comment by dnfield** [comment] 2023-06-14 14:14
Please provide a reproduction of this.

**Comment by chrisgblr** [comment] 2023-06-14 21:47
@burekas7 @dnfield That seems to be the same issue I'm facing:
https://github.com/dnfield/flutter_svg/issues/938

I've added a reproducible example.

**Comment by mostafas-aziz** [comment] 2023-06-27 11:23
Yep, facing the same issue here. Had to revert to using Icon to temporary fix the issue. We have data that disappears when we use SvgPicture within a row

**Comment by dnfield** [comment] 2023-07-06 15:21
Closing in favor of 938

**Closed by dnfield** 2023-07-06 15:21 UTC
