### ISSUE TITLE
Unusual "colorBlendMode" behavior after migrating to 0.17.1

### ISSUE THREAD

**Issue by jcsena** [dnfield/flutter_svg#293] opened 2020-02-12 23:35 UTC
After migrating from version 0.16.1 to version 0.17.1 notice unusual behavior with the color of the vectors and the "colorBlendMode"

v0.16.1 | v0.17.1
------------ | -------------
![0 16 1](https://user-images.githubusercontent.com/4293508/74387061-96ac6d00-4dc5-11ea-86cb-eb684b5ea50b.jpeg) | ![0 17 1](https://user-images.githubusercontent.com/4293508/74387081-a1670200-4dc5-11ea-9bd0-9f0d82c42f35.jpeg)

```dart
SvgPicture.asset(
   "assets/images/shirt_squad.svg",
    color: Colors.red,
    colorBlendMode: BlendMode.colorDodge,
    height: ScreenUtil().setHeight(50.0),
),
```

SVG Source: [Link to download svg](https://www.dropbox.com/s/nu75v4eln1dm3a6/shirt_squad.svg?dl=0)

**Comment by dnfield** [comment] 2020-02-13 01:08
See #290 

There was a bug before 0.17.0 that resulted in color filters being applied incorrectly.  Unfortunately, some people depended on that broken behavior.  The comments in #290 provide a work around that I believe should work for you as well (basically, use a `ColorFiltered` widget with the right matrix).

**Comment by dnfield** [comment] 2020-02-13 01:08
Closing this as a duplicate of #290

**Closed by dnfield** 2020-02-13 01:08 UTC
