### ISSUE TITLE
Type 'AssetBundle' not found

### ISSUE THREAD

**Issue by huakucha** [dnfield/flutter_svg#620] opened 2021-11-22 10:56 UTC
version： 0.23.0+1
problem：

Launching lib/main.dart on Pixel 5 in debug mode...
Running Gradle task 'assembleDebug'...
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_svg-0.23.0+1/lib/svg.dart:325:5: Error: Type 'AssetBundle' not found.
    AssetBundle? bundle,
    ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_svg-0.23.0+1/lib/svg.dart:325:5: Error: 'AssetBundle' isn't a type.
    AssetBundle? bundle,
    ^^^^^^^^^^^

please import ‘import 'package:flutter/services.dart';’ in the error dart file

**Comment by ManoharanTechie** [comment] 2021-11-22 11:21
version： 0.23.0+1
problem：
Find the exact location of the  file  ,edit and remove below lines 
 AssetBundle? bundle,
 
  bundle: bundle,
  
  its working for me.try once

**Comment by huakucha** [comment] 2021-11-23 07:27
Strongly typed in high dart version，AssetBundle does not import automatically...

**Comment by huakucha** [comment] 2021-11-23 07:29
import ‘import 'package:flutter/services.dart';’ file is not a bad thing

**Comment by manoharanpncity** [comment] 2021-11-23 11:24
import ‘import 'package:flutter/services.dart';’ file is not a bad thing.
AssetBundle? bundle, is deprecated in version： 0.23.0+1..

**Comment by huakucha** [comment] 2021-11-24 02:10
[v0.23.0+1/lib/svg.dart](https://github.com/dnfield/flutter_svg/blob/v0.23.0%2B1/lib/svg.dart)
line 325 AssetBundle? bundle,

my flutter version 2.0.3
We are adapting to null safety, so we cannot upgrade to the latest in a short time

**Comment by esmaeil-ahmadipour** [comment] 2021-11-25 15:16
in new version of package at svg.dart file removed (import 'package:flutter/services.dart' show AssetBundle;) and package no found AssetBundle ...

**Comment by huakucha** [comment] 2021-11-26 02:37
in new version of package at svg.dart file removed (import 'package:flutter/services.dart' show AssetBundle;)
but
but
but
the use of "AssetBundle? bundle" still in code,my flutter version 2.0.3 
[https://github.com/dnfield/flutter_svg/blob/master/lib/svg.dart](master)
![image](https://user-images.githubusercontent.com/5646613/143518175-67795f02-5395-49ba-b4e2-08ecc37e4ad5.png)
![image](https://user-images.githubusercontent.com/5646613/143518225-16fd9a13-4d4f-403d-908f-7d7b7cccc32e.png)

How can I eliminate this error message...

**Comment by dnfield** [comment] 2021-11-26 05:14
How does this reproduce for people? I have not encountered it.

**Comment by dnfield** [comment] 2021-12-02 18:57
It looks like maybe in some version of flutter there's a missing import, or how AssetBundle gets exported got changed...? I still haven't reproduced this locally though.

I'm going to close this, but please feel free to ping this issue if you have a clear way to reproduce this error.

**Closed by dnfield** 2021-12-02 18:57 UTC

**Comment by krosiek** [comment] 2022-01-14 09:44
Steps to reproduce:
1. Checkout flutter v2.0.0
2. Create example project
3. Add flutter_svg: ^1.0.0 in pubspec.yaml
4. Add import 'package:flutter_svg/flutter_svg.dart'; in main.dart
5. Build for Android

**Comment by usamaiotexcel** [comment] 2022-11-14 06:24
> Steps to reproduce:
> 
> 1. Checkout flutter v2.0.0
> 2. Create example project
> 3. Add flutter_svg: ^1.0.0 in pubspec.yaml
> 4. Add import 'package:flutter_svg/flutter_svg.dart'; in main.dart
> 5. Build for Android
> 
> Edit: Also notice LayerHandle class used in render_picture.dart is not defined in Flutter 2.2.0 (It is defined in Flutter 2.5.0) so `import 'package:flutter/rendering.dart';` in render_picture.dart does not solve the following problem: `flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-1.0.0/lib/src/render_picture.dart:172:9: Error: Type 'LayerHandle' not found. final LayerHandle<TransformLayer> _transformHandle = `

i'm getting error of LayerHandle in flutter version 2.2.3 .so what should i do for that?
