### ISSUE TITLE
Cannot load svg files with <pattern> tag.

### ISSUE THREAD

**Issue by LHLL** [dnfield/flutter_svg#329] opened 2020-04-14 06:26 UTC
Following image throws runtime exception:
```
flutter: The following assertion was thrown in _getDefinitionPaint:
flutter: Failed to find definition for url(#pattern0)
flutter: This library only supports <defs> and xlink:href references that are defined ahead of their references.
flutter: This error can be caused when the desired definition is defined after the element referring to it
```
Sample SVG file, as you can see `url(#pattern0)` is defined before use:
```
...
<defs>
  <image id="image0" width="1125" height="2436" xlink:href="data:image/png;base64,"{IMAGE_STRING}"/>
<pattern id="pattern0" width="1" height="1" patternContentUnits="objectBoundingBox">
   <use transform="translate(-.00045421 -.23318) scale(.0008897 .0012125)" xlink:href="#image0"/>
</pattern>
<g mask="url(#mask0)">
  <rect x="22" y="17" width="220" height="161" fill="url(#pattern0)"/>
</g>
...
```

**Comment by mariaszek9003** [comment] 2020-05-03 14:13
Yeah, today I experienced same issue.

**Comment by dnfield** [comment] 2020-09-03 16:46
Duplicate of #289

**Closed by dnfield** 2020-09-03 16:46 UTC

**Comment by agueroveraalvaro** [comment] 2021-06-08 16:10
Hello! some solution for this? thanks

**Comment by Rc-Sensussoft** [comment] 2021-12-22 05:21
https://stackoverflow.com/questions/61202925/svgpicture-image-rendering-error-in-flutter

**Comment by hovanhung98hust** [comment] 2022-03-04 04:25
> https://stackoverflow.com/questions/61202925/svgpicture-image-rendering-error-i

> https://stackoverflow.com/questions/61202925/svgpicture-image-rendering-error-in-flutter

this work for me, thanks
