### ISSUE TITLE
Sometimes svg icons are blurry

### ISSUE THREAD

**Issue by jacobsoftdev** [dnfield/flutter_svg#985] opened 2023-09-13 06:16 UTC
Hello everyone!

After migration to version 2.x.x, some SVG icons become blurry. It occurs when I assign a color filter property. Tweaked Blend mode algorithms, for some cases BlendMode.srcIn works fine, but for other cases it makes icon blurry

![code](https://github.com/dnfield/flutter_svg/assets/135833354/d878d384-a9e7-4544-b99b-de35e462fb96)

![Simulator_Screenshot_iPhone_14_Pro_Max_2023_09_13_at_10_23_55](https://github.com/dnfield/flutter_svg/assets/135833354/63beb8a0-4007-48d2-9817-691442569ae1)

**Comment by BottlePumpkin** [comment] 2023-09-14 06:02
me too

**Comment by dnfield** [comment] 2023-09-25 22:17
Please share a complete reproduction. I've seen multiple reports on this but think it might be on an old verison of Flutter. I cannot reproduce this with a recent commit of Flutter on an iPhone or on desktop.

**Comment by jacobsoftdev** [comment] 2023-09-26 11:21
> Please share a complete reproduction. I've seen multiple reports on this but think it might be on an old verison of Flutter. I cannot reproduce this with a recent commit of Flutter on an iPhone or on desktop.

Hi, thank you for your reply and advice. I will try to update to the latest Flutter release. Regarding the steps of reproduction, I cannot provide them. For that colorFilter parameters as in the screenshot, most icons are displayed perfectly, but some icons become blurry. I don't know the cause, maybe due to some errors in dart blend algorithms

**Comment by simonNEON** [comment] 2023-10-04 18:00
Any updates here? Im having the same issues

**Comment by EArminjon** [comment] 2023-11-02 09:15
Same on iOS 17, when using BlendMode.srcIn the svg go blury.

**Comment by EArminjon** [comment] 2023-11-30 16:18
```dart
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

void main() => runApp(const App());

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 2,
      child: Builder(
        builder: (BuildContext context) {
          return Scaffold(
            appBar: AppBar(),
            body: Column(
              children: <Widget>[
                TabBar(
                  tabs: <Widget>[
                    Tab(
                      child: SvgPicture.asset(
                        "asset/common/account.svg",
                        colorFilter: const ColorFilter.mode(
                          Color(0xFF2e4eaa),
                          BlendMode.srcIn,
                        ),
                      ),
                    ),
                    Tab(
                      child: SvgPicture.asset(
                        "asset/common/cart_tab.svg",
                        colorFilter: const ColorFilter.mode(
                          Color(0xFF2e4eaa),
                          BlendMode.srcIn,
                        ),
                      ),
                    ),
                  ],
                ),
                Expanded(child: Container(color: Colors.brown)),
              ],
            ),
          );
        },
      ),
    );
  }
}
```

Icons : 
![cart_tab](https://github.com/dnfield/flutter_svg/assets/37028599/ab85acdb-fbfd-4e0e-9fb4-3be5195e5d04)
![account](https://github.com/dnfield/flutter_svg/assets/37028599/9687b383-7b8b-404b-b97c-e9fdad275a3b)
Result : blury
![Capture d’écran 2023-11-30 à 17 16 53](https://github.com/dnfield/flutter_svg/assets/37028599/189d08fc-f1b1-4cb9-b38f-05fd66fc45aa)

**Comment by dnfield** [comment] 2024-01-17 19:35
I have, again, tried this on a recent commit of Flutter, on both a physical iPhone and a simulator.

I get this:

<img width="457" alt="image" src="https://github.com/dnfield/flutter_svg/assets/8620741/bc32279a-3c6c-488e-a004-15bc5fbc5dfd">


I made it so the icon on the left has the color filter, the icon on the right does not. They look the same to me.

I'm going to close this as not reproducible.

**Closed by dnfield** 2024-01-17 19:35 UTC
