### ISSUE TITLE
SVG shadow not showing in Android but showing in web

### ISSUE THREAD

**Issue by rupamking1** [dnfield/flutter_svg#439] opened 2020-11-01 21:43 UTC
Please help me
SVG shadow not showing in Android but showing in web, how to fix it.

**Comment by dnfield** [comment] 2020-11-02 17:13
Probably a duplicate of #53

**Closed by dnfield** 2020-11-02 17:13 UTC

**Comment by rupamking1** [comment] 2020-11-02 17:31
please add shadow feature

**Comment by dnfield** [comment] 2020-11-02 18:16
Feel free to thumbs up that bug - I'd like to get to it at some point, but it's a little complicated to properly support, and much easier to just "fake" it by drawing your own shadow using Flutter.

**Comment by rupamking1** [comment] 2020-11-02 19:06
@dnfield Thanks this is a good idea. 👍

If you have free time in future please try to make SVG Shadow possible. 😇
