### ISSUE TITLE
SVG circle shadow not rendered

### ISSUE THREAD

**Issue by ened** [dnfield/flutter_svg#66] opened 2018-09-20 22:52 UTC
This SVG renders everything except the shadow of the circle.

[pairing.svg.zip](https://github.com/dnfield/flutter_svg/files/2403327/pairing.svg.zip)

**Comment by dnfield** [comment] 2018-09-22 18:17
Same thing here, uses unsupported filters.

**Comment by dnfield** [comment] 2018-09-26 22:08
Duplicate of #53

**Closed by dnfield** 2018-09-26 22:08 UTC
