### ISSUE TITLE
Support group and use

### ISSUE THREAD

**Issue by strangerxx** [dnfield/flutter_svg#81] opened 2018-11-13 12:55 UTC
I have an svg with multiple groups (<g> elements) and used them (<use> elements)

Example code svg in file
[example.txt](https://github.com/dnfield/flutter_svg/files/2576281/example.txt)

**Comment by dnfield** [comment] 2018-11-24 02:19
Duplicate of #10

**Closed by dnfield** 2018-11-24 02:19 UTC

**Comment by dnfield** [comment] 2018-11-26 07:02
I've pushed some up  changes to the shape_ref branch that should make this work - let meknow how that'slooking to you.

**Comment by strangerxx** [comment] 2019-03-04 12:53
I have error
`
I/flutter (14742): ══╡ EXCEPTION CAUGHT BY SVG ╞═══════════════════════════════════════════════════════════════════════
I/flutter (14742): The following assertion was thrown resolving a single-frame picture stream:
I/flutter (14742): Unable to load asset: assets/1.svg
I/flutter (14742): 
I/flutter (14742): When the exception was thrown, this was the stack:
I/flutter (14742): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
I/flutter (14742): <asynchronous suspension>
I/flutter (14742): #1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67:33)
I/flutter (14742): <asynchronous suspension>
I/flutter (14742): #2      CachingAssetBundle.loadString.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:162:56)
I/flutter (14742): #3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
I/flutter (14742): #4      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:162:27)
I/flutter (14742): #5      AssetBundlePictureProvider._loadAsync (package:flutter_svg/src/picture_provider.dart:421:42)
I/flutter (14742): <asynchronous suspension>
I/flutter (14742): #6      AssetBundlePictureProvider.load (package:flutter_svg/src/picture_provider.dart:408:43)
I/flutter (14742): #7      PictureProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter_svg/src/picture_provider.dart:307:57)
I/flutter (14742): #8      PictureCache.putIfAbsent (package:flutter_svg/src/picture_cache.dart:67:22)
I/flutter (14742): #9      PictureProvider.resolve.<anonymous closure> (package:flutter_svg/src/picture_provider.dart:307:34)
I/flutter (14742): #10     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
I/flutter (14742): #11     PictureProvider.resolve (package:flutter_svg/src/picture_provider.dart:305:24)
I/flutter (14742): #12     _SvgPictureState._resolveImage (package:flutter_svg/svg.dart:557:10)
I/flutter (14742): #13     _SvgPictureState.didChangeDependencies (package:flutter_svg/svg.dart:531:5)
I/flutter (14742): #14     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3862:12)
I/flutter (14742): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #34     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4063:11)
I/flutter (14742): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #36     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
I/flutter (14742): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #42     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (14742): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #55     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (14742): #56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #59     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (14742): #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #64     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #65     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #68     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (14742): #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #74     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (14742): #75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #80     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #81     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (14742): #82     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #88     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #92     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #93     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #98     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #99     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #100    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (14742): #101    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #107    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #110    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (14742): #111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #114    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #115    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #116    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #119    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (14742): #120    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #122    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (14742): #123    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #125    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (14742): #126    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #128    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (14742): #129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #132    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #133    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #134    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (14742): #135    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #136    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #139    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #140    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #141    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #142    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #143    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #144    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #145    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #146    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #147    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (14742): #148    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #149    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #150    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #151    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (14742): #152    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #153    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #154    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #155    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #156    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #157    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #158    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #159    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #160    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (14742): #161    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #162    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #163    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #164    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #165    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #166    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (14742): #167    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #168    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #169    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #171    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #172    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #173    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #174    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #175    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #176    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (14742): #177    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #178    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #179    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #180    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #181    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #182    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #183    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #184    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #185    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #186    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #187    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #188    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (14742): #189    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #190    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #191    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #192    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #193    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #194    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (14742): #195    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (14742): #196    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (14742): #197    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (14742): #198    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (14742): #199    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4659:32)
I/flutter (14742): #200    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter (14742): #201    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (14742): #202    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:508:16)
I/flutter (14742): #203    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (14742): #204    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #205    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #206    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (14742): #207    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (14742): #208    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #209    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #210    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (14742): #211    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (14742): #212    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (14742): #213    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (14742): #214    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #215    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #216    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (14742): #217    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (14742): #218    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (14742): #219    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (14742): #220    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (14742): #221    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (14742): #222    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (14742): #223    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (14742): #224    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
I/flutter (14742): #225    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (14742): #226    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter (14742): #227    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter (14742): #228    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
I/flutter (14742): #229    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
I/flutter (14742): #233    _invoke (dart:ui/hooks.dart:209:10)
I/flutter (14742): #234    _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter (14742): (elided 3 frames from package dart:async)
I/flutter (14742): 
I/flutter (14742): Picture provider: ExactAssetPicture(name: "assets/1.svg", bundle: null, colorFilter: null)
I/flutter (14742): Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#16af5(), name: "assets/1.svg",
I/flutter (14742): colorFilter: null)
I/flutter (14742): ════════════════════════════════════════════════════════════════════════════════════════════════════
`

**Comment by dnfield** [comment] 2019-03-04 14:48
Your assets aren't set up correctly.  Make sure you have your pubspec.yaml set up to tell flutter to include 1.svg
