### ISSUE TITLE
[WEB] Add support to Html renderer

### ISSUE THREAD

**Issue by franarolas** [dnfield/flutter_svg#491] opened 2021-02-15 12:14 UTC
I know that @dnfield was looking to a solution to this, I think that it would be nice if we receive some feedback of the status of that as we can't work with canvaskit renderer in a production environment and we need to use SVGs images(I really don't want to migrate all the images to sprites, as it is the only solution I see to this).

**Comment by leijingxing** [comment] 2021-02-19 02:38
+1

**Comment by dnfield** [comment] 2021-02-19 03:54
The main blocker on this is implementing Canvas.drawPicture, which I am told should be simple

**Comment by franarolas** [comment] 2021-02-19 14:31
> The main blocker on this is implementing Canvas.drawPicture, which I am told should be simple

@dnfield Who is supposed to implement this? Are you working on it?

**Comment by dnfield** [comment] 2021-02-19 15:15
I think @ferhatb is or had someone in mind.

**Comment by franarolas** [comment] 2021-02-19 15:18
@dnfield That's great, I hope it can be implemented as soon as possible, anyways if you need some help maybe I can give a hand.

**Comment by ferhatb** [comment] 2021-02-19 20:17
@franarolas , yes looking at it, likely 2 phases. First we will first add support for drawPicture API which should enable the library, and then optimize so we can take advantage of browsers own rendering in most use cases.

**Comment by franarolas** [comment] 2021-02-25 13:44
> @franarolas , yes looking at it, likely 2 phases. First we will first add support for drawPicture API which should enable the library, and then optimize so we can take advantage of browsers own rendering in most use cases.

Please let us know when it is available, as a lot of people is waiting for this, thank you.

**Comment by dnfield** [comment] 2021-02-25 18:14
I think we can probably close this. drawPicture is now implemented, and a large number of SVGs work on web. There are still some missing features.

From here out, I think we should just open/tag bugs in the flutter/flutter repo for any missing features you might need - e.g. if two point conical gradients are really important for your SVG, this isn't the right repo to open an issue.

**Closed by dnfield** 2021-02-25 18:14 UTC

**Comment by franarolas** [comment] 2021-02-25 20:15
@dnfield That's great, I see this is now merged in version 1.27.0-9(Master channel), we will need to wait until it is implemented in to beta version, it should be around 20th of march. Thank you!

**Comment by duttaoindril** [comment] 2021-03-04 05:26
Wait just to clarify, this package will support flutter_svg on HTML rendering on the master channel?

**Comment by dnfield** [comment] 2021-03-04 05:49
Yes. There are still a handful of features that aren't supported (e.g. two point conical gradients are probably not supported), but many common SVGs should render just fine.

**Comment by duttaoindril** [comment] 2021-03-04 06:30
Ok, awesome! I don't know what two-point conical gradients are, but on canvas kit, this firefox logo renders correctly:

![image](https://user-images.githubusercontent.com/4969854/109920844-c3048700-7c6f-11eb-9d73-7a3dd0406f1a.png)

But on HTML in the master branch it looks like this:

![image](https://user-images.githubusercontent.com/4969854/109920935-da437480-7c6f-11eb-9aca-d208a9cfa3d6.png)

Probably something to check out.

SVG: [Firefox.svg.zip](https://github.com/dnfield/flutter_svg/files/6081294/Firefox.svg.zip)

**Comment by dnfield** [comment] 2021-03-04 08:21
That's not a bug in this library and should be filed in the flutter repo.  It's likely an issue with radial gradients

**Comment by ferhatb** [comment] 2021-03-04 18:02
@duttaoindril Dan is correct that html renderer doesn't support 2 point conical gradient yet. We will land a PR in flutter engine repo to fix this.

**Comment by ferhatb** [comment] 2021-03-04 19:11
@duttaoindril the issue is https://github.com/flutter/flutter/issues/76643.

**Comment by aytunch** [comment] 2021-11-04 18:41
canvast kit increases the load times and network data by a lot and it is not suitable for our production web app. Is Flutter supposed to support html svg rendering? I feel like it not this libraries responsibility?

We can open up an issue in Flutter repo if needed. I think many are waiting to use svgs with html renderers.

**Comment by dnfield** [comment] 2021-11-04 19:38
The web renderer mostly works. There are probably SVGs which do not redner correctly though. Using built in browser support for SVG is possible, but a little tricky to do correctly and without breaking the interface of this package.
