### ISSUE TITLE
Closure call with mismatched arguments: function 'SvgPathStringSource.parseSegments'

### ISSUE THREAD

**Issue by heshesh2010** [dnfield/flutter_svg#344] opened 2020-05-08 15:36 UTC
════════ Exception caught by SVG ═══════════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown resolving a single-frame picture stream:
Closure call with mismatched arguments: function 'SvgPathStringSource.parseSegments'
Receiver: Closure: (_SyncIterator<PathSegmentData>) => bool
Tried calling: SvgPathStringSource.parseSegments()
Found: SvgPathStringSource.parseSegments(_SyncIterator<PathSegmentData>) => bool

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _SyncIterable.iterator (dart:core-patch/core_patch.dart:115:45)
#2      parseSvgPathData (package:path_drawing/src/parse_path.dart:20:38)
#3      _Paths.path (package:flutter_svg/src/svg/parser_state.dart:612:12)
#4      SvgParserState.addShape (package:flutter_svg/src/svg/parser_state.dart:839:31)
...
Picture provider: NetworkPicture("http://upload.wikimedia.org/wikipedia/commons/0/02/SVG_logo.svg", headers: null, colorFilter: null)
Picture key: NetworkPicture("http://upload.wikimedia.org/wikipedia/commons/0/02/SVG_logo.svg", headers: null, colorFilter: null)
════════════════════════════════════════════════════════════════════════════════════════════════════

   Hero(
            tag: category.id,
            child: Container(
                margin: EdgeInsets.only(left: this.marginLeft, right: 20),
                width: 100,
                height: 100,
                decoration: BoxDecoration(
                    borderRadius: BorderRadius.all(Radius.circular(5)),
                    color: Theme.of(context).accentColor),
                child: SvgPicture.network(
                  "http://upload.wikimedia.org/wikipedia/commons/0/02/SVG_logo.svg",
                  placeholderBuilder: (BuildContext context) => Container(
                      padding: const EdgeInsets.all(30.0),
                      child: const CircularProgressIndicator()),
                )),
          ),

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.18.0-13.0.pre, on Mac OS X 10.15.4 19E287, locale en-EG)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

• No issues found!
hesham@HeshamElnemrs-MacBook-Pro Order_client %

**Comment by dnfield** [comment] 2020-05-08 16:25
Does this reproduce consistently? I strongly suspect this was an intermittent network issue where the bytestream from the http request got corrupted, since this is an SVG that is tested as part of the example application. For example, I just now tested the same SVG and did not have an issue.

**Comment by sidlatau** [comment] 2020-05-20 13:47
I just switched to the latest `Flutter 1.19.0-2.0.pre.131 • channel master` and got the same error when running tests. Test runs successfully in `(Flutter 1.18.0-11.1.pre • channel beta)` channel :
```
══╡ EXCEPTION CAUGHT BY SVG ╞═══════════════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown resolving a single-frame picture stream:
Closure call with mismatched arguments: function 'SvgPathStringSource.parseSegments'
Receiver: Closure: (_SyncIterator<PathSegmentData>) => bool
Tried calling: SvgPathStringSource.parseSegments()
Found: SvgPathStringSource.parseSegments(_SyncIterator<PathSegmentData>) => bool

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _SyncIterable.iterator (dart:core-patch/core_patch.dart:117:45)
#2      parseSvgPathData (package:path_drawing/src/parse_path.dart:20:38)
#3      _Paths.path (package:flutter_svg/src/svg/parser_state.dart:612:12)
#4      SvgParserState.addShape (package:flutter_svg/src/svg/parser_state.dart:839:31)
#5      SvgParserState.startElement (package:flutter_svg/src/svg/parser_state.dart:865:12)
#6      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:772:13)
<asynchronous suspension>
#7      SvgParser.parse (package:flutter_svg/parser.dart:14:60)
#8      Svg.fromSvgString (package:flutter_svg/svg.dart:110:25)
#9      Svg.svgPictureStringDecoder (package:flutter_svg/svg.dart:72:36)
#10     SvgPicture.svgStringDecoder.<anonymous closure> (package:flutter_svg/svg.dart:531:15)
#11     AssetBundlePictureProvider._loadAsync (package:flutter_svg/src/picture_provider.dart:457:19)
<asynchronous suspension>
#12     AssetBundlePictureProvider.load (package:flutter_svg/src/picture_provider.dart:435:43)
#13     PictureProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter_svg/src/picture_provider.dart:327:17)
#14     PictureCache.putIfAbsent (package:flutter_svg/src/picture_cache.dart:67:22)
#15     PictureProvider.resolve.<anonymous closure> (package:flutter_svg/src/picture_provider.dart:325:16)
#16     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:41:29)
#17     PictureProvider.resolve (package:flutter_svg/src/picture_provider.dart:322:24)
#18     _SvgPictureState._resolveImage (package:flutter_svg/svg.dart:641:10)
#19     _SvgPictureState.didChangeDependencies (package:flutter_svg/svg.dart:615:5)
#20     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4670:12)
#21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4485:5)
#22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
#23     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5956:32)
...     Normal element mounting (19 frames)
#42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3220:20)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
#45     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4684:11)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
#47     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2632:33)
#48     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1006:18)
#49     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
#50     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
#51     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
#52     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:879:9)
#55     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#56     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:866:27)
#57     WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:563:23)
#58     WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:558:39)
#61     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#62     WidgetTester.pumpAndSettle (package:flutter_test/src/widget_tester.dart:558:27)
#63     main.<anonymous closure>.<anonymous closure> (file:///Users/ts/Documents/github/mworker/flutter_mw/test/documents/document_open_page_test.dart:221:20)
#74     FakeAsync.flushMicrotasks (package:fake_async/fake_async.dart:192:32)
#75     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1099:17)
#76     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1087:35)
(elided 29 frames from dart:async and package:stack_trace)

Picture provider: ExactAssetPicture(name: "assets/images/offline.svg", bundle: null, colorFilter:
  null)
Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#e6892(), name:
  "assets/images/offline.svg", colorFilter: null)
```

**Comment by dnfield** [comment] 2020-05-20 14:21
What version of flutter svg?  These tests are run on every commit to flutter...

**Comment by sidlatau** [comment] 2020-05-20 17:50
> What version of flutter svg? These tests are run on every commit to flutter...

I am using `flutter_svg: ^0.17.4`. 
But it seems it was a cached data problem - I have run `flutter clean` and after that tests passed successfully.

**Comment by dnfield** [comment] 2020-05-20 18:24
I'm going to close this as not-reproducible. I strongly suspect somethign ends up happening where people are getting invalid assets or bad network connections - if anyone can create a consistently reproducible case we can reopen, but even then I suspect it's a bug upstream rather than here.

**Closed by dnfield** 2020-05-20 18:24 UTC
