### ISSUE TITLE
Job for you?

### ISSUE THREAD

**Issue by mlp1802** [dnfield/flutter_svg#382] opened 2020-07-14 15:13 UTC
Hey we would like you to implement this feature and we will pay for it.
We need a SVG image that actions as a background and adapts in height and width to it's foreground.
Same as this example using a png
```
Container PngHeader({Widget child}) {
  return Container(
    child: child,
    decoration: BoxDecoration(
      image: DecorationImage(
        fit: BoxFit.fill,
        image: ExactAssetImage(
          'assets/header.png',
        ),
      ),
    ),
  );
})
````
Here the image acts as a background and will adapt to whatever size the child has.
Is that something that is it possible and someting you would do ?

**Comment by dnfield** [comment] 2020-07-31 17:40
Sorry, I don't have much time for this kind of request at the moment, and since this is not a bug or feature request for the library I'm going to close this.

**Closed by dnfield** 2020-07-31 17:40 UTC
