### ISSUE TITLE
rendering shows lines not in svg definition

### ISSUE THREAD

**Issue by thomas725** [dnfield/flutter_svg#670] opened 2022-02-28 14:20 UTC
Hi there!

I've constructed this simple gear symbol I'd like to use in my flutter app:
```svg
<svg width='98' height='98'><g id='2'><g id='4'><path id='p' d='m49.1,35c-4,0 -7,2 -7.5,2L31,18.5 37,15C38,7.76 38,6 39,0.7 39.7,0 44,0 49.1,0'/><use xlink:href='#p' transform='rotate(-60, 49, 49)'/><use xlink:href='#p' transform='translate(98) scale(-1, 1) rotate(60, 49, 49)'/></g><use xlink:href='#4' transform='translate(98) scale(-1, 1)'/></g><use xlink:href='#2' transform='rotate(180, 49, 49)'/></svg>
```

I've made it's parts overlap to workaround the various svg rendering engines bugs that draw lines if two paths come together exactly, but even the overlap doesn't prevent this library to shows such lines between some of the parts when deployed to android or linux desktop. Deployed to web doesn't show such lines, but it ignores the color specified in the `color` parameter of the `SvgPicture.string()` method, which works fine on Android and desktop.

**Comment by dnfield** [comment] 2022-02-28 17:22
I just tried rendering this on macOS desktop and it looks like this (using Colors.red as the color parameter):

<img width="749" alt="image" src="https://user-images.githubusercontent.com/8620741/156028861-bdb51398-91f2-4465-91ab-1f9b2b00289a.png">

Can you share screenshots of the unexpected rendering and the code you used to create it?

**Comment by dnfield** [comment] 2022-02-28 17:22
(Closing this but will reopen if there are more details shared to reproduce it)

**Comment by thomas725** [comment] 2022-02-28 17:35
Linux Desktop release:
![image](https://user-images.githubusercontent.com/68635351/156030190-f53a133f-e2e3-4ead-a9fc-e1dde3836b22.png)

Android release build:
![image](https://user-images.githubusercontent.com/68635351/156030830-161f78a6-fd39-483a-a1b9-9afc27b44366.png)

code segment used for that button:
```dart
actions: [
          Tooltip(
            child: SizedBox(
              height: 70,
              width: 70,
              child: ElevatedButton(
                onPressed: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (_) => const SettingsScreen(),
                    ),
                  );
                },
                child: SvgPicture.string(
                    "<svg width='98' height='98'><g id='2'><g id='4'><path id='p' d='m49.1,35c-4,0 -7,2 -7.5,2L31,18.5 37,15C38,7.76 38,6 39,0.7 39.7,0 44,0 49.1,0'/><use xlink:href='#p' transform='rotate(-60, 49, 49)'/><use xlink:href='#p' transform='translate(98) scale(-1, 1) rotate(60, 49, 49)'/></g><use xlink:href='#4' transform='translate(98) scale(-1, 1)'/></g><use xlink:href='#2' transform='rotate(180, 49, 49)'/></svg>",
                    color: Colors.white,
                  ),
                style: ElevatedButton.styleFrom(
                    elevation: 0 // , primary: Colors.transparent
                    ),
              ),
            ),
            message: "Settings",
          ),
        ],
      ),
```

**Comment by dnfield** [comment] 2022-03-01 06:11
I'm still not able to reproduce this. I am testing on flutter master channel though.

It's very likely you're hitting some bug in Skia - it's possible that it's been fixed already in the verison of Flutter I'm on. It might help to share your flutter commit hash. Otherwise, it's possible my example is different enough from yours, it might help to give me a small complete program that reproduces this.

**Comment by dnfield** [comment] 2022-03-01 06:11
(I tried on Linux, Chrome, and macOS, debug and release mode on all, and am not seeing these artifacts)

**Comment by thomas725** [comment] 2022-03-01 07:55
```
$ flutter doctor -v                                                                                                                                             ✔  28s  
[✓] Flutter (Channel stable, 2.10.2, on Manjaro Linux 5.16.7-1-MANJARO, locale en_US.UTF-8)
    • Flutter version 2.10.2 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (10 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/thomas/Android/Sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /home/thomas/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.1
    • cmake version 3.22.2
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 64.1.2
    • Dart plugin version 211.7798
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (3 available)
    • Redmi Note 9S (mobile) • 456a90b3 • android-arm64  • Android 11 (API 30)
    • Linux (desktop)        • linux    • linux-x64      • Manjaro Linux 5.16.7-1-MANJARO
    • Chrome (web)           • chrome   • web-javascript • Chromium 98.0.4758.102 Arch Linux

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
Does this contain the flutter commit hash you've asked for? If not, where to find it?

**Comment by dnfield** [comment] 2022-03-01 15:04
It does, I can try to check with that

**Comment by dnfield** [comment] 2022-03-02 00:40
So I tried on the same framework commit and still can't reproduce this on Linux.

Heres' the reproduction I'm trying to use:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: Center(
        // child: SvgPicture.asset('assets/flutter_logo.svg',
        child: SvgPicture.string(
            "<svg width='98' height='98'><g id='2'><g id='4'><path id='p' d='m49.1,35c-4,0 -7,2 -7.5,2L31,18.5 37,15C38,7.76 38,6 39,0.7 39.7,0 44,0 49.1,0'/><use xlink:href='#p' transform='rotate(-60, 49, 49)'/><use xlink:href='#p' transform='translate(98) scale(-1, 1) rotate(60, 49, 49)'/></g><use xlink:href='#4' transform='translate(98) scale(-1, 1)'/></g><use xlink:href='#2' transform='rotate(180, 49, 49)'/></svg>",
            color: Colors.black87,
            width: 500,
            height: 500),
      ),
    ),
  ));
}
```

and `flutter run -d linux -t lib/simple.dart --release` gives me:

<img width="972" alt="image" src="https://user-images.githubusercontent.com/8620741/156272615-97b5204e-1fd6-4279-99bb-df290256a7e1.png">

**Comment by dnfield** [comment] 2022-03-02 17:29
<img width="35" alt="image" src="https://user-images.githubusercontent.com/8620741/156415530-7ccc0b23-f0f8-4447-b1b0-e451ee1a2a2c.png">

On my display I can only see them _very_ faintly but they are there. 

I strongly suspect this is a Skia bug but I'll try to reduce it a bit further.

**Comment by dnfield** [comment] 2022-03-02 22:19
Ok. I looked at this a little more and the problem is with the SVG.

If you plug the SVG itself into Chrome, you get the same issues, especially if you _zoom out_. The artifacts are more noticable as the SVG gets smaller.

![image](https://user-images.githubusercontent.com/8620741/156459212-7866ce74-bd25-454e-9230-af8993fb9c7a.png)


Compared to

![image](https://user-images.githubusercontent.com/8620741/156459261-521dd07f-c408-4fa5-81dd-0d09ffec9789.png)

I suspect that's why you're seeing differences in different Flutter versions, and why adding or removing the sized box can make a bigger difference.

Closing this as WAI. Your SVG needs to be updated if you want to avoid those artifacts.

**Comment by dnfield** [comment] 2022-03-02 22:20
(If I zoom in even further on chrome the artifacts are even less noticeable)

**Closed by dnfield** 2022-03-02 22:19 UTC

**Comment by thomas725** [comment] 2022-03-04 09:35
oh. okey. thanks for taking so much time to help me debug this!

I guess taking advantage of the symmetry of an image can only be done at 90° & 180° in svg, else you get artifacts in some viewers.

I'll have to rethink that approach.

**Comment by thomas725** [comment] 2022-04-11 07:31
for anybody intersted, my svg adventures continued here:
https://stackoverflow.com/questions/71451170/taking-advantage-of-symmetry-in-svg-misunderstanding-or-buggy-renderer-impleme
