### ISSUE TITLE
 UnimplementedError was thrown in parseSvgElement

### ISSUE THREAD

**Issue by DNetORM** [dnfield/flutter_svg#426] opened 2020-09-25 05:55 UTC
══╡ EXCEPTION CAUGHT BY SVG ╞═══════════════════════════════════════════════════════════════════════
The following UnimplementedError was thrown in parseSvgElement:
The <style> element is not implemented in this library.
Style elements are not supported by this library and the requested SVG may not render as intended.
If possible, ensure the SVG uses inline styles and/or attributes (which are supported), or use a
preprocessing utility such as svgcleaner to inline the styles for you.
Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#7256d(), name: "images/test.svg",
  colorFilter: ColorFilter.mode(Color(0xffff7a17), BlendMode.srcIn))
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by dnfield** [comment] 2020-09-25 06:56
Duplicate of #105

**Closed by dnfield** 2020-09-25 06:56 UTC
