### ISSUE TITLE
What is the performance vs rendering pngs ?

### ISSUE THREAD

**Issue by danielwalczak** [dnfield/flutter_svg#370] opened 2020-06-26 21:39 UTC
Im wondering what is actually performance of rendering simply svg images versus pngs? which one would be better.

**Comment by dnfield** [comment] 2020-06-26 21:57
This question is really hard to answer as is, and it's not a bug, so I'm going to close it :)

I will say, it depends on what you're rendering and whether you need to optimize for memory or CPU usage, and whether you need to display the graphic at various resolutions.

Another consideration is whether your SVG file is just embedded images or not, whether it's using lots of complicated/expensive shaders or not, and a bunch of other considerations.

**Closed by dnfield** 2020-06-26 21:57 UTC
