### ISSUE TITLE
Handle image both png/jpg and svg

### ISSUE THREAD

**Issue by IchordeDionysos** [dnfield/flutter_svg#212] opened 2019-08-10 16:43 UTC
Hey,
has anyone some tips on how to handle if an image from e.g. Cloud Storage can be either SVG or png/jpg? (Especially if the Content-Type can only be decided from the HTTP header)

**Comment by IchordeDionysos** [comment] 2019-08-10 16:46
@dnfield Is there anything planned to merge this widget with the Flutter `Image` Widget, so we as developers do not have to care about the content type of an image, just like we don't have to care about whether it's a GIF or a static image?

**Comment by dnfield** [comment] 2019-08-10 16:52
No.  You would have to work out in your code what kind of asset it is.  You could probably write a wrapper around this to do that.

This package will likely never be merged into the framework.  There are other plans to support a vector based format, but xml is a heavy dependency to force on everyone

**Comment by dnfield** [comment] 2019-10-22 00:53
It may be worth creating another library that would handle this kind of thing, but content-type sniffing can be tricky and sometimes domain specific.  I'm going to close this though since it's not a bug for flutter_svg.

**Closed by dnfield** 2019-10-22 00:53 UTC
