### ISSUE TITLE
Svg was not loaded sucessfully in my Flutter App 

### ISSUE THREAD

**Issue by laxit-ramani** [dnfield/flutter_svg#946] opened 2023-06-16 07:06 UTC
[https://cdn.coinranking.com/jkDf8sQbY/usdc.svg](https://cdn.coinranking.com/jkDf8sQbY/usdc.svg)

This image I am able to run this in browsers yet it's showing black in my Flurrer app widget. there is no runtime exception thrown. Could you please help me with this as well? Thank you in advance.

**Comment by dnfield** [comment] 2023-06-16 15:33
There should be a warning log printed that the `<style>` element is not supported. This SVG uses classes/css styling. Dupe of #105

**Closed by dnfield** 2023-06-16 15:33 UTC
