### ISSUE TITLE
Undo deprecation of color parameter

### ISSUE THREAD

**Issue by xinoxapps** [dnfield/flutter_svg#972] opened 2023-08-04 07:49 UTC
Can the color parameter be recovered to its full glory?

```
          SvgPicture.asset(
            titleIcon,
            colorFilter: const ColorFilter.mode(Colors.green, BlendMode.srcIn),
            width: 18,
            height: 18,
          ),
```

vs

```
          SvgPicture.asset(
            titleIcon,
            color: Colors.green,
            width: 18,
            height: 18,
          ),
```
👍

**Comment by dnfield** [comment] 2023-08-04 15:39
Duplicate of https://github.com/dnfield/flutter_svg/issues/856

**Closed by dnfield** 2023-08-04 15:39 UTC

**Comment by dnfield** [comment] 2023-08-04 15:45
The TL;DR for that issue:

- The parameter is deprecated but not going anywhere anytime soon.
- It's deprecated because it's confusing and potentially very expensive to use.
- Anyone can trivially write a method to create the right kind of color filter if you commonly use `srcIn` blending.
- I'd like users to think about whether they want a `colorMapper` or `colorFilter`. In almost all cases you should prefer a `colorMapper` where that will work.
