### ISSUE TITLE
CanvasKit / HTML renderer support

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [dnfield/flutter_svg#522] opened 2021-03-24 08:19 UTC
## Problem

Currently, there is the following problem with `flutter_svg`:

* On web using the *HTML renderer*, `flutter_svg` **does not** work. Instead, you need to use [`Image.network`](https://api.flutter.dev/flutter/widgets/Image/Image.network.html) for SVGs.
* On web using the *CanvasKit renderer*, `flutter_svg` **does** work. Now, you _cannot_ use `Image.network` (because it only supports raster images using CanvasKit).

## Solution

You can use [this solution](https://stackoverflow.com/a/66777112/6509751) for **detecting** whether the app is running on the CanvasKit backend. If so, the `SvgPicture` widget should act like normal.  
If **not**, i.e. when using the HTML renderer, we can simply return the appropriate `Image` widget for rendering SVGs, e.g.:

* `SvgPicture.asset` → `Image.asset`
* `SvgPicture.network` → `Image.network`

This will also support the auto-mode for web renderers.

**Comment by dnfield** [comment] 2021-03-24 11:20
I think this is a duplicate of #491

**Closed by dnfield** 2021-03-24 11:20 UTC

**Comment by creativecreatorormaybenot** [comment] 2021-03-24 12:19
@dnfield No, it is not. The issue you linked asks for Flutter SVG support using the HTML renderer.

I am saying that Flutter web supports SVGs *already* using the HTML renderer. We just need to forward to `Image` when not using CanvasKit.

**Comment by dnfield** [comment] 2021-03-24 18:10
That workaround has many surprising limitations and it's not one I want to adopt for this package.

On newer versions of flutter we can support this without doing that.

**Comment by creativecreatorormaybenot** [comment] 2021-03-24 18:17
Thanks @dnfield. I misread https://github.com/dnfield/flutter_svg/issues/491#issuecomment-786101184 actually.
