### ISSUE TITLE
Bad state: Expected to find Drawable with id url

### ISSUE THREAD

**Issue by epomatti** [dnfield/flutter_svg#159] opened 2019-05-03 13:14 UTC
I'm trying to render the SVG from **Buy Me a Coffee** but I get an error. Since it renders in Chrome and Firefox I assume the SVG file is ok?

I'm running `Flutter 1.2.1` and `flutter_svg 0.12.4` plugin (tried 0.13.0 but can't find flutter SDK 1.5.9-pre.94)

Link to SVG: https://www.buymeacoffee.com/assets/img/BMC-btn-logo.svg

I simply do this in the code:

`new SvgPicture.asset('assets/BMC-btn-logo.svg')`

And I get the exception bellow. 

```
I/flutter ( 4620): ══╡ EXCEPTION CAUGHT BY SVG ╞═══════════════════════════════════════════════════════════════════════
I/flutter ( 4620): The following StateError was thrown resolving a single-frame picture stream:
I/flutter ( 4620): Bad state: Expected to find Drawable with id url(#path0_fill).
I/flutter ( 4620): Have ids: (url(#Canvas), url(#Group), url(#Combined Shape))
```

Full error stack attached: [exception.log](https://github.com/dnfield/flutter_svg/files/3141999/exception.log)

**Comment by dnfield** [comment] 2019-05-03 16:10
Duplicate of #102 

I don't have an ETA for that fix.  A work around is to move the `<defs>` element up so that the parser encounters it before getting the references.

**Closed by dnfield** 2019-05-03 16:10 UTC

**Comment by dnfield** [comment] 2019-05-03 17:39
(If you'd like to try a PR for that fix please feel free to! It shouldn't be super difficult, I just have som eother things I'm busy with right now, and usually the work around is good enough)

**Comment by Soft2-Dev** [comment] 2022-11-17 22:29
naaa el mismo el error estoy consumiendo una api y no tengo control del sgv

**Comment by Shodric** [comment] 2022-11-20 16:43
@Soft2-Dev  estamos en la misma
