### ISSUE TITLE
App crashes when adding svg icons

### ISSUE THREAD

**Issue by Djihanegh** [dnfield/flutter_svg#636] opened 2021-12-24 07:39 UTC
Hello, i'm trying to add icons in the bottom nav bar, some of them are causing crash the app

```
<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 25 25"><g transform="translate(0.5 0.5)"><path d="M4.27,8.87a4.445,4.445,0,1,1,.33,0A1.818,1.818,0,0,0,4.27,8.87Z" transform="translate(7.56 2)" fill="none" stroke="#9098b1" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" stroke-dasharray="0 0"/><path d="M1.815,7.242a9.766,9.766,0,0,0,10.01,0c2.42-1.62,2.42-4.26,0-5.87a9.812,9.812,0,0,0-10.01,0C-.605,2.993-.605,5.632,1.815,7.242Z" transform="translate(5.345 13.188)" fill="none" stroke="#9098b1" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" stroke-dasharray="0 0"/><path d="M24,0V24H0V0Z" transform="translate(24 24) rotate(180)" fill="none" stroke="#9098b1" stroke-width="1" opacity="0"/></g></svg> 
```

I'am exporting them from adobeXD
and this is the code snippet :

```dart
SvgPicture.asset(
                  imageUrl,
                  color: navBarIndex == index ? KPrimaryColor : KNBColor,
                  width: 10,
                  height: 20,
                  placeholderBuilder: (BuildContext context) =>
                      Container(child: LoadingWidget()),
                ),
```

What's the problem here ?and how to avoid the app crash ?

**Comment by dnfield** [comment] 2022-01-11 00:29
The problem is the `stroke-dasharray="0 0"`, which seems to be causing an infinite loop :\

**Comment by dnfield** [comment] 2022-01-11 00:41
Fixed in 65dbfc6

**Closed by dnfield** 2022-01-11 00:41 UTC

**Comment by unique-gautam-yadav** [comment] 2024-02-25 08:49
@dnfield Still getting this issue in `flutter_svg: ^2.0.10`

**Comment by dnfield** [comment] 2024-02-25 15:42
Please file an issue with an SVG that causes a crash or lockup
