### ISSUE TITLE
Svg render doesn't right

### ISSUE THREAD

**Issue by definev** [dnfield/flutter_svg#431] opened 2020-10-11 16:29 UTC
Icon Extra in app
![Screenshot_1602433553](https://user-images.githubusercontent.com/62325868/95684075-34885e00-0c19-11eb-9c0b-ae7cb244a655.png)
Right shape
![Extra](https://user-images.githubusercontent.com/62325868/95684103-6c8fa100-0c19-11eb-9521-6f76d0fc6fff.png)

Svg code:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Creator: CorelDRAW 2019 (64-Bit) -->
<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" width="77px" height="93px" version="1.1" style="shape-rendering:geometricPrecision; text-rendering:geometricPrecision; image-rendering:optimizeQuality; fill-rule:evenodd; clip-rule:evenodd"
viewBox="0 0 6.526 7.921"
 xmlns:xlink="http://www.w3.org/1999/xlink">
 <defs>
  <style type="text/css">
   <![CDATA[
    .str0 {stroke:#323C44;stroke-width:0.256;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:2.61313}
    .fil0 {fill:none}
    .fil1 {fill:#323C44;fill-rule:nonzero}
   ]]>
  </style>
 </defs>
 <g id="Layer_x0020_1">
  <metadata id="CorelCorpID_0Corel-Layer"/>
  <g id="_2281990148432">
   <path class="fil0 str0" d="M6.39 7.32l-6.262 0m0 0.474l0 -1.334c0,-0.137 0.089,-0.248 0.198,-0.248l4.889 0 0.47 0.461"/>
   <path class="fil0 str0" d="M3.938 7.794l0 -1.334c0,-0.137 0.089,-0.248 0.199,-0.248m1.394 -1.847l0.661 0c0.109,0 0.198,0.114 0.198,0.249l0 3.18"/>
   <path class="fil0 str0" d="M5.587 4.365l-3.787 0c-0.081,0 -0.156,0.085 -0.166,0.187l-0.09 1.001"/>
   <path class="fil0 str0" d="M3.725 4.365c-0.081,0 -0.157,0.085 -0.166,0.187l-0.09 0.995"/>
   <g>
    <path class="fil1" d="M0.384 0.256c-0.071,0 -0.128,-0.058 -0.128,-0.128 0,-0.071 0.057,-0.128 0.128,-0.128l0 0.256zm0.622 0l-0.622 0 0 -0.256 0.622 0 0 0.256zm0 -0.256c0.07,0 0.127,0.057 0.127,0.128 0,0.07 -0.057,0.128 -0.127,0.128l0 -0.256zm1.436 2.984c-0.025,0.066 -0.099,0.099 -0.165,0.074 -0.065,-0.025 -0.099,-0.099 -0.074,-0.164l0.239 0.09zm0.221 -0.581l-0.221 0.581 -0.239 -0.09 0.221 -0.582 0.239 0.091zm-0.239 -0.091c0.025,-0.066 0.099,-0.099 0.165,-0.074 0.066,0.025 0.099,0.099 0.074,0.165l-0.239 -0.091zm-1.414 -0.343c-0.058,0.04 -0.138,0.027 -0.178,-0.031 -0.041,-0.057 -0.028,-0.137 0.03,-0.178l0.148 0.209zm0.507 -0.359l-0.507 0.359 -0.148 -0.209 0.508 -0.359 0.147 0.209zm-0.147 -0.209c0.057,-0.041 0.137,-0.027 0.178,0.03 0.041,0.058 0.027,0.138 -0.031,0.179l-0.147 -0.209zm3.138 1.522c0.023,0.067 -0.012,0.139 -0.079,0.163 -0.066,0.023 -0.139,-0.012 -0.163,-0.078l0.242 -0.085zm-0.206 -0.587l0.206 0.587 -0.242 0.085 -0.206 -0.587 0.242 -0.085zm-0.242 0.085c-0.023,-0.067 0.012,-0.14 0.079,-0.163 0.066,-0.023 0.139,0.012 0.163,0.078l-0.242 0.085zm1.821 -0.603c0.057,0.042 0.069,0.122 0.027,0.179 -0.042,0.057 -0.122,0.068 -0.179,0.026l0.152 -0.205zm-0.499 -0.37l0.499 0.37 -0.152 0.205 -0.499 -0.37 0.152 -0.205zm-0.152 0.205c-0.057,-0.042 -0.069,-0.122 -0.027,-0.179 0.042,-0.057 0.122,-0.069 0.179,-0.026l-0.152 0.205zm1.168 -1.653c0.071,0 0.128,0.057 0.128,0.128 0,0.07 -0.057,0.128 -0.128,0.128l0 -0.256zm-0.622 0l0.622 0 0 0.256 -0.622 0 0 -0.256zm0 0.256c-0.07,0 -0.128,-0.058 -0.128,-0.128 0,-0.071 0.058,-0.128 0.128,-0.128l0 0.256zm-1.152 0l-1.233 0 0 -0.256 1.233 0 0.128 0.128 -0.128 0.128zm0 -0.256c0.071,0 0.128,0.057 0.128,0.128 0,0.07 -0.057,0.128 -0.128,0.128l0 -0.256zm-1.233 1.489l0 -0.256 0 0 0.057 -0.001 0.056 -0.005 0.055 -0.007 0.055 -0.009 0.053 -0.013 0.053 -0.014 0.051 -0.018 0.05 -0.02 0.049 -0.022 0.048 -0.024 0.046 -0.027 0.045 -0.029 0.043 -0.03 0.042 -0.033 0.04 -0.035 0.039 -0.037 0.036 -0.038 0.035 -0.04 0.033 -0.042 0.031 -0.043 0.029 -0.045 0.026 -0.046 0.024 -0.048 0.023 -0.049 0.019 -0.05 0.018 -0.051 0.015 -0.053 0.012 -0.053 0.01 -0.055 0.007 -0.055 0.004 -0.056 0.001 -0.057 0.256 0 -0.002 0.07 -0.005 0.069 -0.009 0.068 -0.012 0.067 -0.015 0.066 -0.018 0.064 -0.022 0.064 -0.024 0.062 -0.027 0.06 -0.03 0.059 -0.033 0.057 -0.036 0.055 -0.037 0.053 -0.041 0.052 -0.043 0.049 -0.045 0.047 -0.047 0.045 -0.049 0.043 -0.052 0.04 -0.053 0.038 -0.055 0.036 -0.057 0.032 -0.059 0.03 -0.06 0.028 -0.062 0.024 -0.063 0.022 -0.065 0.018 -0.066 0.015 -0.067 0.012 -0.068 0.009 -0.069 0.005 -0.07 0.002 0 0zm0 0c-0.071,0 -0.128,-0.057 -0.128,-0.128 0,-0.071 0.057,-0.128 0.128,-0.128l0 0.256zm-1.233 -1.489l0 0.256 0.128 -0.128 0.001 0.057 0.004 0.056 0.007 0.055 0.01 0.055 0.012 0.053 0.015 0.053 0.018 0.051 0.019 0.05 0.022 0.049 0.025 0.048 0.026 0.046 0.029 0.045 0.031 0.043 0.033 0.042 0.035 0.04 0.036 0.038 0.039 0.037 0.04 0.035 0.042 0.033 0.043 0.03 0.045 0.029 0.046 0.027 0.048 0.024 0.049 0.022 0.05 0.02 0.051 0.018 0.053 0.014 0.053 0.013 0.054 0.009 0.056 0.007 0.056 0.005 0.057 0.001 0 0.256 -0.07 -0.002 -0.069 -0.005 -0.068 -0.009 -0.067 -0.012 -0.066 -0.015 -0.065 -0.018 -0.063 -0.022 -0.062 -0.024 -0.06 -0.028 -0.059 -0.03 -0.057 -0.032 -0.055 -0.036 -0.053 -0.038 -0.052 -0.04 -0.049 -0.043 -0.047 -0.045 -0.045 -0.047 -0.043 -0.049 -0.041 -0.052 -0.037 -0.053 -0.036 -0.055 -0.033 -0.057 -0.03 -0.059 -0.027 -0.06 -0.024 -0.062 -0.022 -0.064 -0.018 -0.064 -0.015 -0.066 -0.012 -0.067 -0.009 -0.068 -0.005 -0.069 -0.002 -0.07 0.128 -0.128zm-0.128 0.128c0,-0.071 0.057,-0.128 0.128,-0.128 0.07,0 0.128,0.057 0.128,0.128l-0.256 0zm1.361 0.128l-1.233 0 0 -0.256 1.233 0 0 0 0 0.256zm0 -0.256c0.07,0 0.128,0.057 0.128,0.128 0,0.07 -0.058,0.128 -0.128,0.128l0 -0.256z"/>
   </g>
   <path class="fil0 str0" d="M5.531 4.365c-0.081,0 -0.156,0.085 -0.166,0.187l-0.15 1.66"/>
   <g>
    <path class="fil1" d="M2.227 5.717l-1.027 0 0 -0.256 1.027 0 0 0 0 0.256zm0 -0.256c0.07,0 0.127,0.058 0.127,0.128 0,0.071 -0.057,0.128 -0.127,0.128l0 -0.256zm0.463 0.464l-0.253 0 0 0 0 -0.01 -0.001 -0.011 -0.001 -0.01 -0.002 -0.01 -0.002 -0.01 -0.003 -0.01 -0.003 -0.009 -0.004 -0.01 -0.004 -0.009 -0.005 -0.009 -0.005 -0.009 -0.005 -0.008 -0.006 -0.008 -0.006 -0.008 -0.007 -0.008 -0.007 -0.007 -0.007 -0.007 -0.008 -0.007 -0.008 -0.006 -0.008 -0.006 -0.009 -0.006 -0.009 -0.005 -0.009 -0.004 -0.009 -0.005 -0.009 -0.003 -0.01 -0.004 -0.01 -0.002 -0.01 -0.003 -0.011 -0.002 -0.01 -0.001 -0.011 -0.001 -0.011 0 0 -0.256 0.024 0.001 0.023 0.002 0.024 0.003 0.022 0.004 0.023 0.005 0.022 0.006 0.021 0.008 0.021 0.008 0.021 0.009 0.019 0.01 0.02 0.012 0.019 0.012 0.018 0.013 0.017 0.013 0.017 0.015 0.016 0.015 0.015 0.016 0.015 0.017 0.014 0.017 0.013 0.019 0.012 0.018 0.011 0.02 0.01 0.02 0.01 0.021 0.008 0.021 0.007 0.021 0.007 0.022 0.005 0.023 0.004 0.023 0.003 0.023 0.002 0.024 0 0.023 0 0zm0 0c0,0.071 -0.056,0.128 -0.126,0.128 -0.07,0 -0.127,-0.057 -0.127,-0.128l0.253 0zm-0.253 0.287l0 -0.287 0.253 0 0 0.287 -0.126 0.127 -0.127 -0.127zm0.253 0c0,0.07 -0.056,0.127 -0.126,0.127 -0.07,0 -0.127,-0.057 -0.127,-0.127l0.253 0zm-1.826 -0.128l1.7 0 0 0.255 -1.7 0 -0.127 -0.127 0.127 -0.128zm0 0.255c-0.07,0 -0.127,-0.057 -0.127,-0.127 0,-0.071 0.057,-0.128 0.127,-0.128l0 0.255zm0.126 -0.414l0 0.287 -0.253 0 0 -0.287 0 0 0.253 0zm-0.253 0c0,-0.07 0.057,-0.127 0.127,-0.127 0.07,0 0.126,0.057 0.126,0.127l-0.253 0zm0.463 -0.464l0 0.256 0 0 -0.011 0 -0.01 0.001 -0.011 0.001 -0.01 0.002 -0.01 0.003 -0.01 0.002 -0.01 0.004 -0.009 0.003 -0.01 0.005 -0.009 0.004 -0.009 0.005 -0.008 0.006 -0.008 0.006 -0.008 0.006 -0.008 0.007 -0.007 0.007 -0.007 0.007 -0.007 0.008 -0.006 0.008 -0.006 0.008 -0.006 0.008 -0.005 0.009 -0.004 0.009 -0.005 0.009 -0.003 0.01 -0.003 0.009 -0.003 0.01 -0.003 0.01 -0.001 0.01 -0.002 0.01 -0.001 0.011 0 0.01 -0.253 0 0.001 -0.023 0.002 -0.024 0.003 -0.023 0.004 -0.023 0.005 -0.023 0.006 -0.022 0.008 -0.021 0.008 -0.021 0.009 -0.021 0.011 -0.02 0.011 -0.02 0.012 -0.018 0.013 -0.019 0.014 -0.017 0.014 -0.017 0.016 -0.016 0.016 -0.015 0.016 -0.015 0.018 -0.013 0.018 -0.013 0.019 -0.012 0.019 -0.012 0.02 -0.01 0.02 -0.009 0.022 -0.008 0.021 -0.008 0.022 -0.006 0.022 -0.005 0.023 -0.004 0.023 -0.003 0.024 -0.002 0.023 -0.001 0 0zm0 0c0.07,0 0.127,0.058 0.127,0.128 0,0.071 -0.057,0.128 -0.127,0.128l0 -0.256z"/>
   </g>
   <g>
    <path class="fil1" d="M4.406 5.717l-1.027 0 0 -0.256 1.027 0 0 0 0 0.256zm0 -0.256c0.07,0 0.127,0.058 0.127,0.128 0,0.071 -0.057,0.128 -0.127,0.128l0 -0.256zm0.463 0.464l-0.253 0 0 0 0 -0.01 -0.001 -0.011 -0.001 -0.01 -0.002 -0.01 -0.002 -0.01 -0.003 -0.01 -0.003 -0.009 -0.004 -0.01 -0.004 -0.009 -0.005 -0.009 -0.005 -0.009 -0.005 -0.008 -0.006 -0.008 -0.006 -0.008 -0.007 -0.008 -0.007 -0.007 -0.007 -0.007 -0.008 -0.007 -0.008 -0.006 -0.008 -0.006 -0.009 -0.006 -0.009 -0.005 -0.009 -0.004 -0.009 -0.005 -0.01 -0.003 -0.009 -0.004 -0.01 -0.002 -0.01 -0.003 -0.011 -0.002 -0.01 -0.001 -0.011 -0.001 -0.011 0 0 -0.256 0.024 0.001 0.023 0.002 0.023 0.003 0.023 0.004 0.023 0.005 0.021 0.006 0.022 0.008 0.021 0.008 0.02 0.009 0.02 0.01 0.02 0.012 0.018 0.012 0.019 0.013 0.017 0.013 0.017 0.015 0.016 0.015 0.015 0.016 0.015 0.017 0.013 0.017 0.013 0.019 0.013 0.018 0.011 0.02 0.01 0.02 0.009 0.021 0.009 0.021 0.007 0.021 0.006 0.022 0.006 0.023 0.004 0.023 0.003 0.023 0.002 0.024 0 0.023 0 0zm0 0c0,0.071 -0.056,0.128 -0.126,0.128 -0.07,0 -0.127,-0.057 -0.127,-0.128l0.253 0zm-0.253 0.287l0 -0.287 0.253 0 0 0.287 -0.126 0.127 -0.127 -0.127zm0.253 0c0,0.07 -0.056,0.127 -0.126,0.127 -0.07,0 -0.127,-0.057 -0.127,-0.127l0.253 0zm-1.826 -0.128l1.7 0 0 0.255 -1.7 0 -0.127 -0.127 0.127 -0.128zm0 0.255c-0.07,0 -0.127,-0.057 -0.127,-0.127 0,-0.071 0.057,-0.128 0.127,-0.128l0 0.255zm0.126 -0.414l0 0.287 -0.253 0 0 -0.287 0 0 0.253 0zm-0.253 0c0,-0.07 0.057,-0.127 0.127,-0.127 0.069,0 0.126,0.057 0.126,0.127l-0.253 0zm0.463 -0.464l0 0.256 0 0 -0.011 0 -0.011 0.001 -0.01 0.001 -0.01 0.002 -0.01 0.003 -0.01 0.002 -0.01 0.004 -0.01 0.003 -0.009 0.005 -0.009 0.004 -0.009 0.005 -0.008 0.006 -0.009 0.006 -0.008 0.006 -0.007 0.007 -0.008 0.007 -0.007 0.007 -0.006 0.008 -0.007 0.008 -0.005 0.008 -0.006 0.008 -0.005 0.009 -0.005 0.009 -0.004 0.009 -0.003 0.01 -0.004 0.009 -0.002 0.01 -0.003 0.01 -0.002 0.01 -0.001 0.01 -0.001 0.011 0 0.01 -0.253 0 0.001 -0.023 0.001 -0.024 0.003 -0.023 0.005 -0.023 0.005 -0.023 0.006 -0.022 0.007 -0.021 0.009 -0.021 0.009 -0.021 0.011 -0.02 0.011 -0.02 0.012 -0.018 0.013 -0.019 0.014 -0.017 0.014 -0.017 0.015 -0.016 0.016 -0.015 0.017 -0.015 0.018 -0.013 0.018 -0.013 0.019 -0.012 0.019 -0.012 0.02 -0.01 0.02 -0.009 0.021 -0.008 0.022 -0.008 0.022 -0.006 0.022 -0.005 0.023 -0.004 0.023 -0.003 0.023 -0.002 0.024 -0.001 0 0zm0 0c0.07,0 0.126,0.058 0.126,0.128 0,0.071 -0.056,0.128 -0.126,0.128l0 -0.256z"/>
   </g>
  </g>
 </g>
</svg>
```

**Comment by dnfield** [comment] 2020-10-12 04:30
Duplicate of #105

**Closed by dnfield** 2020-10-12 04:30 UTC
