### ISSUE TITLE
kindly update the package to support flutter latest version and dont show black image 

### ISSUE THREAD

**Issue by fisforfaheem** [dnfield/flutter_svg#1035] opened 2024-02-06 17:27 UTC

**Comment by dnfield** [comment] 2024-02-06 17:31
I'm not sure what the problem is here? Can you provide reproduction steps?

**Comment by fisforfaheem** [comment] 2024-02-06 22:33
i have to use png file...as cant show an image on onboarding page...if it
svg

**Comment by dnfield** [comment] 2024-02-06 22:42
I'm sorry but I still don't understand what problem you're encountering. If you can provide a SVG file that does not render and it's not a duplicate of some other bug I'll reopen.

**Closed by dnfield** 2024-02-06 22:42 UTC

**Comment by fisforfaheem** [comment] 2024-02-06 23:10
![Screenshot_20240207-041023.png](https://github.com/dnfield/flutter_svg/assets/35878088/1ec3e374-0b6d-49dd-ba56-78dc82f451f6)

**Comment by fisforfaheem** [comment] 2024-02-06 23:11
See

**Comment by yykou** [comment] 2024-05-30 07:24
I have the same problem.An SVG image on a web page that can be opened normally will result in a black area when loaded using the latest version of the library, and the image cannot be displayed.

SVG image path：https://ccdn1.goodq.top/caches/3802cdfcb59f037aa40858825f9f3e24/aHR0cHM6Ly9zdmdzLjR2eC5uZXQvcWZ5LWNvbnRlbnQvdXBsb2Fkcy8yMDIxLzA0LzBhYTNlNzQwYzU0ZjMxZjY0YmIyODE3OTc2ZjQwODJkLnN2Zw_p_p100_p_3D_p_p100_p_3D.svg

code：
`SvgPicture.network(
                'https://ccdn1.goodq.top/caches/3802cdfcb59f037aa40858825f9f3e24/aHR0cHM6Ly9zdmdzLjR2eC5uZXQvcWZ5LWNvbnRlbnQvdXBsb2Fkcy8yMDIxLzA0LzBhYTNlNzQwYzU0ZjMxZjY0YmIyODE3OTc2ZjQwODJkLnN2Zw_p_p100_p_3D_p_p100_p_3D.svg',
                semanticsLabel: 'A shark?!',
                width: 50.0,
                height: 50.0,
                placeholderBuilder: (BuildContext context) => Container(
                    padding: const EdgeInsets.all(30.0),
                    child: const CircularProgressIndicator()),
              )`

最终显示的效果：
![Clipboard - 2024年5月30日下午3点24分](https://github.com/dnfield/flutter_svg/assets/21016582/62a7e604-1fc7-4612-a458-e974206d4e5c)

**Comment by fisforfaheem** [comment] 2024-05-30 18:44
They are not helping

**Comment by fisforfaheem** [comment] 2024-05-30 22:21
exported fro mfigma
