### ISSUE TITLE
Gradient not rendered correctly

### ISSUE THREAD

**Issue by JigneshPatel23** [dnfield/flutter_svg#712] opened 2022-05-19 06:28 UTC
SVG gradient-based rendering - image path is getting too thin compared to expected.

Without gradient, SVG works as expected, and also, this SVG works fine on any other SVG viewers.
e.g. https://www.svgviewer.dev/

## Actual SVG Rendering
![SVG-Actual](https://user-images.githubusercontent.com/7347854/169224692-9a33898a-7c8e-43f6-a231-e2e6b618c56e.jpeg)

## Expected SVG Rendering

![SVG-Expected](https://user-images.githubusercontent.com/7347854/169224656-6e3a3b64-39be-4566-9b8f-93095c8bdfb7.png)

## Input SVG File

```
<svg width="25" height="24" viewBox="0 0 25 24" fill="none" xmlns="http://www.w3.org/2000/svg">

<defs>
<linearGradient id="paint0_linear_2076_12087" x1="6" y1="2" x2="21.3154" y2="3.96642" gradientUnits="userSpaceOnUse">
<stop stop-color="#33C2FF"/>
<stop offset="1" stop-color="#0093E6"/>
</linearGradient>
</defs>

<path d="M8 2C6.89543 2 6 2.88943 6 3.994C6 7.96584 6 16.9191 6 22L11.8146 16.5333C12.1997 16.1712 12.7985 16.1698 13.1834 16.532C14.7402 17.9968 18.4576 21.4935 19 21.993V4.00001C19 2.89544 18.1046 2.00001 17 2.00001L8 2Z" stroke="url(#paint0_linear_2076_12087)" stroke-width="2.5" stroke-linejoin="round"/>

</svg>

```

**Comment by JigneshPatel23** [comment] 2022-05-20 12:58
Yes, @dnfield, I am on the current latest version `flutter_svg: ^1.0.3`

**Comment by dnfield** [comment] 2022-05-20 17:12
Ahh the problem is that I havenot done a release..  Can you see if this gets resolved by using a more recent version from master? :)

**Comment by dnfield** [comment] 2022-05-23 16:23
Published 1.1.0 with what should be a fix for this today. Please try it.

**Closed by dnfield** 2022-05-23 16:23 UTC

**Comment by dnfield** [comment] 2022-05-23 16:24
(Based on a local test this is fixed on 1.1.0)

**Comment by dobeerman** [comment] 2022-06-30 21:05
`flutter_svg: ^1.1.1` doesn't render gradient :disappointed:

**Comment by fernandes456** [comment] 2022-07-21 13:24
@dobeerman check if your SVG defines the tag `defs` before of use it.
We had the same problem, and we fixed it by changing the SVG. No update in flutter_svg was required.

**Comment by dobeerman** [comment] 2022-07-21 13:28
@fernandes456 the SVG file has `defs`

```svg
<svg width="390"
  height="330"
  viewBox="0 0 390 330"
  fill="none"
  xmlns="http://www.w3.org/2000/svg">
  <rect width="390"
    height="500"
    transform="translate(0 -170)"
    fill="white"/>
  <path fill-rule="evenodd"
    clip-rule="evenodd"
    d="M390 269.67V-170H0L0 183.708C59.2507 220.478 146.081 231.927 235.949 243.776C287.863 250.621 340.791 257.599 390 269.67Z"
    fill="url(#paint0_linear_181_6929)"
    fill-opacity="0.5"/>
  <defs>
    <linearGradient id="paint0_linear_181_6929"
      x1="38.6334"
      y1="837.339"
      x2="510.232"
      y2="318.072"
      gradientUnits="userSpaceOnUse">
      <stop stop-color="#1400FF"/>
      <stop offset="1"
        stop-color="#FFDC62"/>
    </linearGradient>
  </defs>
</svg>
```

**Comment by mefryar** [comment] 2022-09-05 19:58
@dobeerman Just to be explicit, what @fernandes456 is suggesting is manually editing your SVG to look like the snippet below, so that the gradient `<defs>` are defined before they are referenced:
```svg
<svg width="390"
  height="330"
  viewBox="0 0 390 330"
  fill="none"
  xmlns="http://www.w3.org/2000/svg">
  <rect width="390"
    height="500"
    transform="translate(0 -170)"
    fill="white"/>
  <path fill-rule="evenodd"
    clip-rule="evenodd"
    d="M390 269.67V-170H0L0 183.708C59.2507 220.478 146.081 231.927 235.949 243.776C287.863 250.621 340.791 257.599 390 269.67Z"
    fill="url(#paint0_linear_181_6929)"
    fill-opacity="0.5"/>
  <defs>
    <linearGradient id="paint0_linear_181_6929"
      x1="38.6334"
      y1="837.339"
      x2="510.232"
      y2="318.072"
      gradientUnits="userSpaceOnUse">
      <stop stop-color="#1400FF"/>
      <stop offset="1"
        stop-color="#FFDC62"/>
    </linearGradient>
  </defs>
</svg>
```

**Comment by fernandes456** [comment] 2022-09-09 21:21
Like that @dobeerman 

```SVG
<svg width="390"
  height="330"
  viewBox="0 0 390 330"
  fill="none"
  xmlns="http://www.w3.org/2000/svg">
  <rect width="390"
    height="500"
    transform="translate(0 -170)"
    fill="white"/>
  <defs>
    <linearGradient id="paint0_linear_181_6929"
      x1="38.6334"
      y1="837.339"
      x2="510.232"
      y2="318.072"
      gradientUnits="userSpaceOnUse">
      <stop stop-color="#1400FF"/>
      <stop offset="1"
        stop-color="#FFDC62"/>
    </linearGradient>
  </defs>
  <path fill-rule="evenodd"
    clip-rule="evenodd"
    d="M390 269.67V-170H0L0 183.708C59.2507 220.478 146.081 231.927 235.949 243.776C287.863 250.621 340.791 257.599 390 269.67Z"
    fill="url(#paint0_linear_181_6929)"
    fill-opacity="0.5"/>

</svg>
```

**Comment by mefryar** [comment] 2022-09-14 22:02
Thanks, @fernandes456! I realized I made the mistake of re-pasting the original instead of the corrected version. I've edited my original comment.
