### ISSUE TITLE
Can SVG behave like an Icon and change colors?

### ISSUE THREAD

**Issue by jeffersondarcy** [dnfield/flutter_svg#345] opened 2020-05-11 16:50 UTC
I am trying to use a SvgPicture inside BottomNavigationBar and it should change colors depending on if it's selected or unselected. This works with Icons out of the box - would it also be possible with SVG?

**Comment by dnfield** [comment] 2020-05-11 17:49
It would be helpful to see a reproduction of what you're trying to do.

My understanding is that `BottomNavigationBarItem` has both an `icon` and `activeIcon` widget, and that's how that works - I don't see why SVG should need anything special for that.

**Comment by PiN73** [comment] 2020-06-03 21:05
Alternatively you can use color passed by BottomNavigationBar from context:
```
BottomNavigationBarItem(
  icon: Builder(
    builder: (context) {
      return SvgPicture.asset(
        'my_icon.svg',
        color: IconTheme.of(context).color,
      );
    },
  ),
),
```

**Comment by dnfield** [comment] 2020-08-14 02:07
Going to close this as not a bug in flutter_svg.

**Closed by dnfield** 2020-08-14 02:07 UTC
