### ISSUE TITLE
Size of the <use> element should be taken into account when converting SVG to PNG

### ISSUE THREAD

**Issue by Grooviz** [dnfield/flutter_svg#455] opened 2020-11-24 13:36 UTC
## Use case:

We want to download a PNG version of an SVG such as:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 3300 3300" stroke="none">
  <symbol id="module" viewBox="0 0 512 512">
    <g>
      <path d="M414.41,24.123C398.333,8.042,378.963,0,356.315,0H82.228C59.58,0,40.21,8.042,24.126,24.123 C8.045,40.207,0.003,59.576,0.003,82.225v274.084c0,22.647,8.042,42.018,24.123,58.102c16.084,16.084,35.454,24.126,58.102,24.126 h274.084c22.648,0,42.018-8.042,58.095-24.126c16.084-16.084,24.126-35.454,24.126-58.102V82.225 C438.532,59.576,430.49,40.204,414.41,24.123z" fill="rgb(255,87,34)"/>
    </g>
  </symbol>
  <rect width="1000" height="1000" style="fill:rgb(0,0,0);fill-opacity:1" />
  <use href="#module" x="100" y="100" width="80" height="80" />
  <use href="#module" x="200" y="100" width="80" height="80" />
  <use href="#module" x="300" y="100" width="80" height="80" />
  <use href="#module" x="400" y="100" width="80" height="80" />
</svg>
```

where we `<use>` a symbol, specifying its `width` and `height`.

![image](https://user-images.githubusercontent.com/44902700/100100572-50f6f780-2e61-11eb-9b0a-cf8c018d6559.png)

## What should happen?

The downloaded PNG should be the same image as the SVG version

## What happened?

The symbol is not resized in the downloaded PNG:

![image](https://user-images.githubusercontent.com/44902700/100101296-5739a380-2e62-11eb-94e4-a107f781d177.png)

## How to reproduce?

```
import 'dart:typed_data';
import 'dart:ui' as ui;
import 'dart:html' as html;

import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center(
          child: ElevatedButton(
            onPressed: () {
              svgToPng(svgSample).then((ByteData data) {
                downloadBytes(
                  data.buffer
                      .asUint8List(data.offsetInBytes, data.lengthInBytes),
                  'png',
                );
              });
            },
            child: const Text('Download PNG'),
          ),
        ),
      ),
    );
  }
}

  const String svgSample = '''<?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
  <svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 3300 3300" stroke="none">
    <symbol id="module" viewBox="0 0 512 512">
      <g>
        <path d="M414.41,24.123C398.333,8.042,378.963,0,356.315,0H82.228C59.58,0,40.21,8.042,24.126,24.123 C8.045,40.207,0.003,59.576,0.003,82.225v274.084c0,22.647,8.042,42.018,24.123,58.102c16.084,16.084,35.454,24.126,58.102,24.126 h274.084c22.648,0,42.018-8.042,58.095-24.126c16.084-16.084,24.126-35.454,24.126-58.102V82.225 C438.532,59.576,430.49,40.204,414.41,24.123z" fill="rgb(255,87,34)"/>
      </g>
    </symbol>
    <rect width="1000" height="1000" style="fill:rgb(0,0,0);fill-opacity:1" />
    <use href="#module" x="100" y="100" width="80" height="80" />
    <use href="#module" x="200" y="100" width="80" height="80" />
    <use href="#module" x="300" y="100" width="80" height="80" />
    <use href="#module" x="400" y="100" width="80" height="80" />
  </svg>
''';

Future<ByteData> svgToPng(String rawSvg) async {
  final DrawableRoot svgRoot = await svg.fromSvgString(rawSvg, rawSvg);
  final ui.Picture picture = svgRoot.toPicture(
    size: const Size(1000, 1000),
    clipToViewBox: true,
  );
  final ui.Image image = await picture.toImage(1000, 1000);
  final ByteData data = await image.toByteData(format: ui.ImageByteFormat.png);
  return data;
}

void downloadBytes(Uint8List bytes, String ext) {
  final List<Uint8List> data = [bytes];
  final html.Blob blob = html.Blob(data);
  final String url = html.Url.createObjectUrlFromBlob(blob);
  final html.Element anchor =
      html.document.createElement('a') as html.AnchorElement
        ..href = url
        ..style.display = 'none'
        ..download = 'qr.$ext';
  html.document.body.children.add(anchor);
  anchor.click();
  html.document.body.children.remove(anchor);
  html.Url.revokeObjectUrl(url);
}
```

Thank you! 😀

**Comment by Grooviz** [comment] 2020-11-24 23:27
For the time being, we have a workaround:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 3300 3300" stroke="none">
  <symbol id="module" viewBox="0 0 512 512">
    <g>
      <path d="M414.41,24.123C398.333,8.042,378.963,0,356.315,0H82.228C59.58,0,40.21,8.042,24.126,24.123 C8.045,40.207,0.003,59.576,0.003,82.225v274.084c0,22.647,8.042,42.018,24.123,58.102c16.084,16.084,35.454,24.126,58.102,24.126 h274.084c22.648,0,42.018-8.042,58.095-24.126c16.084-16.084,24.126-35.454,24.126-58.102V82.225 C438.532,59.576,430.49,40.204,414.41,24.123z" fill="rgb(255,87,34)"/>
    </g>
  </symbol>
  <rect width="1000" height="1000" style="fill:rgb(0,0,0);fill-opacity:1" />
  <use href="#module" transform="translate(100, 100), scale(0.15625, 0.15625)" />
  <use href="#module" transform="translate(200, 100), scale(0.15625, 0.15625)" />
  <use href="#module" transform="translate(300, 100), scale(0.15625, 0.15625)" />
  <use href="#module" transform="translate(400, 100), scale(0.15625, 0.15625)" />
</svg>
```
Instead of {x, y, width, height}, we may use `scale` and `translate` transformation.

Note: If all the `<use>` elements have the same size, the transform can also be applied to the `<g>` element of the `<symbol>` instead:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 3300 3300" stroke="none">
  <symbol id="module" viewBox="0 0 512 512">
    <g transform="scale(0.15625, 0.15625)">
      <path d="M414.41,24.123C398.333,8.042,378.963,0,356.315,0H82.228C59.58,0,40.21,8.042,24.126,24.123 C8.045,40.207,0.003,59.576,0.003,82.225v274.084c0,22.647,8.042,42.018,24.123,58.102c16.084,16.084,35.454,24.126,58.102,24.126 h274.084c22.648,0,42.018-8.042,58.095-24.126c16.084-16.084,24.126-35.454,24.126-58.102V82.225 C438.532,59.576,430.49,40.204,414.41,24.123z" fill="rgb(255,87,34)"/>
    </g>
  </symbol>
  <rect width="1000" height="1000" style="fill:rgb(0,0,0);fill-opacity:1" />
  <use href="#module" x="100" y="100" />
  <use href="#module" x="200" y="100" />
  <use href="#module" x="300" y="100" />
  <use href="#module" x="400" y="100" />
</svg>
```

**Comment by dnfield** [comment] 2020-11-25 01:14
I think this is a duplicate of #366

**Closed by dnfield** 2020-11-25 01:14 UTC
