### ISSUE TITLE
Abnormal stroke width rendering.

### ISSUE THREAD

**Issue by dev-zhang** [dnfield/flutter_svg#383] opened 2020-07-15 10:51 UTC
I have an SVG picture,
It looks like this in the browser:
![](https://cdn.jsdelivr.net/gh/dev-zhang/imgHosting/img/20200715185207.jpg)

In my Flutter project, it looks like this:
![](https://cdn.jsdelivr.net/gh/dev-zhang/imgHosting/img/20200715184014.jpg)
You can see the stroke becomes thinner.

The complete SVG code is like this
```
<?xml version="1.0" encoding="UTF-8"?>
<svg width="48px" height="48px" viewBox="0 0 48 48" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 56.2 (81672) - https://sketch.com -->
    <title>个人中心_我的收藏@2x</title>
    <desc>Created with Sketch.</desc>
    <g id="页面-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="icon+图片" transform="translate(-418.000000, -4546.000000)">
            <g id="编组-4" transform="translate(256.000000, 4456.000000)">
                <g id="编组-55复制-9" transform="translate(162.000000, 90.000000)">
                    <rect id="个人中心_我的收藏" stroke="#979797" fill="#D8D8D8" opacity="0" x="0.5" y="0.5" width="47" height="47"></rect>
                    <g id="编组-18" transform="translate(5.000000, 6.000000)" stroke-linecap="round" stroke-linejoin="round" stroke-width="3">
                        <path d="M22.6353292,33.2052524 L29.4409607,36.8559701 C30.3218053,37.3296762 31.3510976,36.56639 31.1829662,35.5645768 L29.1891737,23.7009998 L37.6359318,15.2981558 C38.348645,14.5901074 37.9557916,13.353952 36.9707875,13.2074881 L25.2975466,11.47754 L20.0772713,0.68356801 C19.636849,-0.227856003 18.3639712,-0.227856003 17.9227287,0.68356801 L12.7024534,11.47754 L1.02921246,13.2074881 C0.0442084233,13.353952 -0.348644975,14.5901074 0.364068184,15.2981558 L8.81082632,23.7009998" id="Stroke-45" stroke="#2F2A01"></path>
                        <path d="M9.01148206,24 L7.01817683,35.5968493 C6.85015562,36.5761388 7.87959287,37.3222641 8.75986006,36.8592083 L21,28.7033712" id="Stroke-45" stroke="#FFCA00"></path>
                    </g>
                </g>
            </g>
        </g>
    </g>
</svg>
```

When I added `stroke-linecap="round" stroke-linejoin="round" stroke-width="3"` from `<g id="编组-18" transform="translate(5.000000, 6.000000)" stroke-linecap="round" stroke-linejoin="round" stroke-width="3">` to the `path` tag, in my Flutter project, the width of the stroke looks the same as it does in the browser.
![](https://cdn.jsdelivr.net/gh/dev-zhang/imgHosting/img/20200715183907.jpg)

The modified complete SVG code is as follows
```
<?xml version="1.0" encoding="UTF-8"?>
<svg width="48px" height="48px" viewBox="0 0 48 48" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 56.2 (81672) - https://sketch.com -->
    <title>个人中心_我的收藏@2x</title>
    <desc>Created with Sketch.</desc>
    <g id="页面-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="icon+图片" transform="translate(-418.000000, -4546.000000)">
            <g id="编组-4" transform="translate(256.000000, 4456.000000)">
                <g id="编组-55复制-9" transform="translate(162.000000, 90.000000)">
                    <rect id="个人中心_我的收藏" stroke="#979797" fill="#D8D8D8" opacity="0" x="0.5" y="0.5" width="47" height="47"></rect>
                    <g id="编组-18" transform="translate(5.000000, 6.000000)" stroke-linecap="round" stroke-linejoin="round" stroke-width="3">
                        <path d="M22.6353292,33.2052524 L29.4409607,36.8559701 C30.3218053,37.3296762 31.3510976,36.56639 31.1829662,35.5645768 L29.1891737,23.7009998 L37.6359318,15.2981558 C38.348645,14.5901074 37.9557916,13.353952 36.9707875,13.2074881 L25.2975466,11.47754 L20.0772713,0.68356801 C19.636849,-0.227856003 18.3639712,-0.227856003 17.9227287,0.68356801 L12.7024534,11.47754 L1.02921246,13.2074881 C0.0442084233,13.353952 -0.348644975,14.5901074 0.364068184,15.2981558 L8.81082632,23.7009998" id="Stroke-45" stroke="#2F2A01" stroke-linecap="round" stroke-linejoin="round" stroke-width="3"></path>
                        <path d="M9.01148206,24 L7.01817683,35.5968493 C6.85015562,36.5761388 7.87959287,37.3222641 8.75986006,36.8592083 L21,28.7033712" id="Stroke-45" stroke="#FFCA00" stroke-linecap="round" stroke-linejoin="round" stroke-width="3"></path>
                    </g>
                </g>
            </g>
        </g>
    </g>
</svg>
```

**Comment by dnfield** [comment] 2020-07-31 17:38
Duplicate of #176

**Closed by dnfield** 2020-07-31 17:38 UTC
