### ISSUE TITLE
Colors isn't being parsed correctly

### ISSUE THREAD

**Issue by feinstein** [dnfield/flutter_svg#303] opened 2020-03-03 23:35 UTC
I am no SVG wizard, but I found this [example](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color) on how to set a color, and so I did something like this:

```
<g color="white">
    <path fill="currentColor" class="st0" d="M15.35,2.62C13.6
```

But this SVG thows an exception at svg/colors.dart at line 139:

```dart
throw StateError('Could not parse "$colorString" as a color.');
```

As `colorString` came as `currentColor`.

IntelliJ IDEA supports this kind on color, as I can see my SVG changing color on the IDE, so I guess this is a bug on `flutter_svg` or this isn't implemented yet and should have a different error message.

**Comment by dnfield** [comment] 2020-03-04 00:01
Duplicate of #31

**Closed by dnfield** 2020-03-04 00:01 UTC
