### ISSUE TITLE
Could you export 'render_picture.dart'

### ISSUE THREAD

**Issue by huakucha** [dnfield/flutter_svg#622] opened 2021-11-30 03:50 UTC
We customize the relative display effect, Could you export 'render_picture.dart'?
[render_picture.dart](https://github.com/dnfield/flutter_svg/blob/master/lib/src/render_picture.dart)

**Comment by dnfield** [comment] 2021-11-30 03:57
Could you explain a bit more about what you want from that?  I don't think it's a good idea to export from this package but maybe from a new one....  The problem is it's app private API so I can change it more easily.

**Comment by huakucha** [comment] 2021-11-30 05:45
I want to use PictureStream to monitor the first frame when resolving, and make an image easeIn, Placeholder easeOut effect
`result = Stack(
        fit: StackFit.passthrough,
        alignment: Alignment.center,
        children: [
          FadeWidget(
            child: image,
            duration: const Duration(milliseconds: 700),
            curve: Curves.easeIn,
          ),
          FadeWidget(
            child: _svgPlaceholderBuilder(context),
            duration: const Duration(milliseconds: 700),
            curve: Curves.easeOut,
            direction: AnimationDirection.reverse,
          )
        ]`

**Comment by dnfield** [comment] 2021-11-30 05:55
I'd kind of like to get rid of `PictureStream` because SVGs only ever return a single frame in this library and I never intend to support animation. But supporting a frame transition would be fine. I'd have to think a bit about the best way to do that.

**Comment by dnfield** [comment] 2022-01-11 20:46
Going to close this as WAI. I'd really rather avoid exposing more API from this package.

**Closed by dnfield** 2022-01-11 20:46 UTC
