### ISSUE TITLE
chrome and inappview can load svg url normally, but flutter_svg cannot

### ISSUE THREAD

**Issue by nerverwind** [dnfield/flutter_svg#1034] opened 2024-01-30 06:49 UTC
svg: https://images-dev.sft-api.io/image/chain/5/contract/0x41fb9b28df4800d018b834e0bd6b58e7b33b4ac1/token/33
SvgPicture.network('https://images-dev.sft-api.io/image/chain/5/contract/0x41fb9b28df4800d018b834e0bd6b58e7b33b4ac1/token/33')

got this:

<img width="337" alt="image" src="https://github.com/dnfield/flutter_svg/assets/10102473/fa2e193c-2a2a-4bdf-9cdf-75c836d66e6d">

chrome:
<img width="864" alt="image" src="https://github.com/dnfield/flutter_svg/assets/10102473/d522a1f7-e591-41a6-a28d-885cdc7edfa8">

inappwebview:
<img width="400" alt="image" src="https://github.com/dnfield/flutter_svg/assets/10102473/b9eb82d5-701e-4ebc-a8e1-2c9f28572cca">

https://jakearchibald.github.io/svgomg/
<img width="1465" alt="image" src="https://github.com/dnfield/flutter_svg/assets/10102473/2b5de088-d688-45ac-85a0-8a2f356f27cc">

what I do wrong? Pls help me, thanks.

**Comment by dnfield** [comment] 2024-01-30 06:54
Pretty sure this is related to #820 although it's userSpaceOnUse. Anyway, something probably is weird with the patterns here.

**Comment by nerverwind** [comment] 2024-01-30 07:06
> Pretty sure this is related to #820 although it's userSpaceOnUse. Anyway, something probably is weird with the patterns here.

OK， the problems seem similar to me. Any solution or suggestion?

**Comment by dnfield** [comment] 2024-02-20 16:55
I'm closing this as a duplicate of 820.

The solution for now is to not use SVGs that have complicated pattern elements in them - it's almost always something that can be simplified down to a less expensive operation. I don't know when I'll have time to work on implementing 820 at the moment, and it's not super easy to implement unfortunately.

**Closed by dnfield** 2024-02-20 16:55 UTC
