### ISSUE TITLE
SVG exported from figma are not being rendered correctly

### ISSUE THREAD

**Issue by makinghappen** [dnfield/flutter_svg#866] opened 2023-02-16 17:23 UTC
SVG exported from figma are not being rendered correctly

Gradients are not rendered:
![logo](https://user-images.githubusercontent.com/100151762/219439955-02efeb2e-c074-43ed-959f-d68601099ed9.svg)

One of the layers is not rendered
![wallpaper](https://user-images.githubusercontent.com/100151762/219439964-ba9b9a9d-2bd2-4312-98b1-c4157abdfc59.svg)

**Comment by dnfield** [comment] 2023-02-16 19:09
This is essentially a duplicate of #53. Both of these SVGs are extensively using filters. It's really not clear to me why they are and this is a really good example of the spec allowing for things that are _terrible_ for performance :\

**Comment by dnfield** [comment] 2023-02-16 19:09
Duplicate of #53

**Closed by dnfield** 2023-02-16 19:09 UTC
