### ISSUE TITLE
please fix this issue: I/flutter ( 7924): unhandled element filter; Picture key: Svg loader

### ISSUE THREAD

**Issue by fisforfaheem** [dnfield/flutter_svg#966] opened 2023-07-18 07:48 UTC
this is so worrying

**Comment by MarvinQuevedo** [comment] 2023-07-22 20:01
I have the same problem, I can't show the original svg image

**Comment by fisforfaheem** [comment] 2023-07-23 09:22
please someone fix it :(

**Comment by dnfield** [comment] 2023-09-14 16:52
duplicate of #53

**Closed by dnfield** 2023-09-14 16:52 UTC
