### ISSUE TITLE
this  svg render fail 

### ISSUE THREAD

**Issue by Darren-chenchen** [dnfield/flutter_svg#314] opened 2020-03-20 14:27 UTC
```
<?xml version="1.0" encoding="UTF-8"?>
<svg width="750px" height="208px" viewBox="0 0 750 208" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 61.2 (89653) - https://sketch.com -->
    <title>bg_miaosha</title>
    <desc>Created with Sketch.</desc>
    <defs>
        <linearGradient x1="50%" y1="0%" x2="50%" y2="100%" id="linearGradient-1">
            <stop stop-color="#FE6248" offset="0%"></stop>
            <stop stop-color="#FE4954" offset="100%"></stop>
        </linearGradient>
        <path d="M66,0 C90.300529,0 110,19.699471 110,44 L110,44 L730,44 C741.045695,44 750,52.954305 750,64 L750,208 L0,208 L0,64 C-1.3527075e-15,52.954305 8.954305,44 20,44 L22,44 C22,19.699471 41.699471,0 66,0 Z" id="path-2"></path>
        <path d="M-5.68434189e-14,208.000002 C30.3885393,199.585373 55.2968386,191.585373 74.7248981,184 C157.158374,151.815178 215.08277,162.328153 262.494836,184 C358.754784,228 483.478972,134 497.736242,44 C507.241088,-16 591.329007,38.6666674 750,208.000002 L-5.68434189e-14,208.000002 Z" id="path-4"></path>
        <filter x="-3.3%" y="-14.4%" width="106.7%" height="126.7%" filterUnits="objectBoundingBox" id="filter-5">
            <feOffset dx="0" dy="-2" in="SourceAlpha" result="shadowOffsetOuter1"></feOffset>
            <feGaussianBlur stdDeviation="8" in="shadowOffsetOuter1" result="shadowBlurOuter1"></feGaussianBlur>
            <feComposite in="shadowBlurOuter1" in2="SourceAlpha" operator="out" result="shadowBlurOuter1"></feComposite>
            <feColorMatrix values="0 0 0 0 0   0 0 0 0 0   0 0 0 0 0  0 0 0 0.100060096 0" type="matrix" in="shadowBlurOuter1"></feColorMatrix>
        </filter>
        <circle id="path-6" cx="460" cy="0" r="221"></circle>
        <filter x="-5.7%" y="-5.2%" width="111.3%" height="111.3%" filterUnits="objectBoundingBox" id="filter-7">
            <feOffset dx="0" dy="2" in="SourceAlpha" result="shadowOffsetOuter1"></feOffset>
            <feGaussianBlur stdDeviation="8" in="shadowOffsetOuter1" result="shadowBlurOuter1"></feGaussianBlur>
            <feComposite in="shadowBlurOuter1" in2="SourceAlpha" operator="out" result="shadowBlurOuter1"></feComposite>
            <feColorMatrix values="0 0 0 0 0   0 0 0 0 0   0 0 0 0 0  0 0 0 0.0639750874 0" type="matrix" in="shadowBlurOuter1"></feColorMatrix>
        </filter>
        <path d="M535,44 L730,44 C741.045695,44 750,52.954305 750,64 L750,208 L750,208 L535,208 L515,125.384586 L535,44 Z" id="path-8"></path>
        <filter x="-6.4%" y="-7.9%" width="111.1%" height="115.9%" filterUnits="objectBoundingBox" id="filter-9">
            <feOffset dx="-2" dy="0" in="SourceAlpha" result="shadowOffsetOuter1"></feOffset>
            <feGaussianBlur stdDeviation="4" in="shadowOffsetOuter1" result="shadowBlurOuter1"></feGaussianBlur>
            <feColorMatrix values="0 0 0 0 0.907438859   0 0 0 0 0.184376472   0 0 0 0 0.154427143  0 0 0 1 0" type="matrix" in="shadowBlurOuter1"></feColorMatrix>
        </filter>
        <filter x="-4.7%" y="-5.5%" width="107.7%" height="111.0%" filterUnits="objectBoundingBox" id="filter-10">
            <feOffset dx="2" dy="0" in="SourceAlpha" result="shadowOffsetInner1"></feOffset>
            <feComposite in="shadowOffsetInner1" in2="SourceAlpha" operator="arithmetic" k2="-1" k3="1" result="shadowInnerInner1"></feComposite>
            <feColorMatrix values="0 0 0 0 1   0 0 0 0 1   0 0 0 0 1  0 0 0 0.498361014 0" type="matrix" in="shadowInnerInner1"></feColorMatrix>
        </filter>
    </defs>
    <g id="🔪切图" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="背景" transform="translate(-110.000000, -2233.000000)">
            <g id="bg_miaosha" transform="translate(110.000000, 2233.000000)">
                <g>
                    <mask id="mask-3" fill="white">
                        <use xlink:href="#path-2"></use>
                    </mask>
                    <use id="形状结合" fill="url(#linearGradient-1)" xlink:href="#path-2"></use>
                    <g id="路径-2" mask="url(#mask-3)">
                        <use fill="black" fill-opacity="1" filter="url(#filter-5)" xlink:href="#path-4"></use>
                        <use fill-opacity="0.078612" fill="#FFEEEB" fill-rule="evenodd" xlink:href="#path-4"></use>
                    </g>
                    <g id="椭圆形" mask="url(#mask-3)">
                        <use fill="black" fill-opacity="1" filter="url(#filter-7)" xlink:href="#path-6"></use>
                        <use fill-opacity="0.0986123252" fill="#FFEEEB" fill-rule="evenodd" xlink:href="#path-6"></use>
                    </g>
                    <g id="矩形" mask="url(#mask-3)">
                        <use fill="black" fill-opacity="1" filter="url(#filter-9)" xlink:href="#path-8"></use>
                        <use fill="#FFEEEB" fill-rule="evenodd" xlink:href="#path-8"></use>
                        <use fill="black" fill-opacity="1" filter="url(#filter-10)" xlink:href="#path-8"></use>
                    </g>
                </g>
            </g>
        </g>
    </g>
</svg>
```
![image](https://user-images.githubusercontent.com/16269032/77173090-f3ecba00-6af9-11ea-8ef4-9bca583b4f9a.png)

**Comment by dnfield** [comment] 2020-03-20 14:40
Duplicate of #159

**Closed by dnfield** 2020-03-20 14:40 UTC
