### ISSUE TITLE
The <style> element is not implemented in this library

### ISSUE THREAD

**Issue by sultanmyrza** [dnfield/flutter_svg#425] opened 2020-09-25 05:07 UTC
```
flutter: The following UnimplementedError was thrown in parseSvgElement:
flutter: The <style> element is not implemented in this library.
flutter:
flutter: Style elements are not supported by this library and the requested SVG may not render as intended.
flutter: If possible, ensure the SVG uses inline styles and/or attributes (which are supported), or use a
flutter: preprocessing utility such as svgcleaner to inline the styles for you.
```
https://i.imgur.com/0yAEfAW.mp4

any plans to add support for <style> element? 
or I should ask designers to not to use <style> element on their svg designs?

**Comment by dnfield** [comment] 2020-09-25 05:26
duplicate of #105 

Most applications have options to output without using `<style>`, or there are post processing utilities to help with that too.

**Closed by dnfield** 2020-09-25 05:26 UTC
