### ISSUE TITLE
Svg icons are delayed

### ISSUE THREAD

**Issue by Demirzekk** [dnfield/flutter_svg#840] opened 2023-02-03 10:01 UTC
My assets svg icons are delayed loading. 
 flutter_svg: ^2.0.0+1
if I use ^1.1.6, there is no delayed

**Comment by levi956** [comment] 2023-02-03 10:10
Same!!!!! 
Almost pushed into production.

**Comment by Dohmanlechx** [comment] 2023-02-03 10:33
Same, but the reason might be that I removed the `precachePicture` function as it no longer existed and I don't understand how to replace them. Created issue: https://github.com/dnfield/flutter_svg/issues/841

**Comment by appinteractive** [comment] 2023-02-03 13:17
Also saw that loading, looks horrible. I did not remove anything, just upgraded and my app was loading like web in the 90`s

**Comment by appinteractive** [comment] 2023-02-03 13:20
okay seems like that issue only exists in debug mode, did not validate it till now. #809

**Comment by blue492** [comment] 2023-02-03 15:46
same issue here
flutter_svg: ^2.0.0+1
flutter: 3.7.1

**Comment by Dohmanlechx** [comment] 2023-02-03 15:56
> okay seems like that issue only exists in debug mode, did not validate it till now. #809

Just tried in profile mode, and yeah it was instantaneous, but for the big main logo it can be a biiiiit delayed. Just if I had a way to precache or await until the app loaded the SVG.

But for small icons, yes instantaneous. This should be documented tho, if it isn't already.

**Comment by dnfield** [comment] 2023-02-03 16:29
Duplicate of #837

**Closed by dnfield** 2023-02-03 16:29 UTC
