### ISSUE TITLE
Some SVG stop displaying with Flutter 2.10.0

### ISSUE THREAD

**Issue by ycherniavskyi** [dnfield/flutter_svg#661] opened 2022-02-05 22:56 UTC
After upgrading Flutter from 2.8.1 to 2.10.0 next SVG stop displaying:
```
<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2">
  <g transform="matrix(2.17391 0 0 2.04082 -2547.826 -500)">
    <path style="fill:none" d="M1172 245h46v49h-46z"/>
    <clipPath id="a">
      <path d="M1172 245h46v49h-46z"/>
    </clipPath>
    <g clip-path="url(#a)">
      <path d="M25.54 37.52c-4.63 0-9-4.13-11.92-6.94L13 30l-.55-.58C8.39 25.15 1.61 18 8.37 11.27c1.81-1.81 4-1.69 6.12.31 1.18 1.13 2.56 3.11 2.58 5a3.19 3.19 0 0 1-.93 2.35 7.122 7.122 0 0 1-1.05.83c-.82.57-.88.68-.82.86a19.08 19.08 0 0 0 3.43 4.69 19.08 19.08 0 0 0 4.69 3.43c.18.06.3 0 .86-.82.25-.354.528-.689.83-1a3.204 3.204 0 0 1 2.35-.92c1.86 0 3.84 1.4 5 2.58 2 2.09 2.12 4.32.31 6.12a8.625 8.625 0 0 1-6.2 2.82ZM11.17 12.23a1.704 1.704 0 0 0-1.22.62c-4.83 4.82-1 9.65 4.1 15l.57.6.54.51c5.36 5.1 10.19 8.93 15 4.1.67-.67 1.09-1.5-.35-3a6 6 0 0 0-3.38-1.9.87.87 0 0 0-.75.29 4.874 4.874 0 0 0-.58.74c-.57.82-1.63 2.35-3.56 1.6l-.13-.07a21.102 21.102 0 0 1-5.28-3.86 21.232 21.232 0 0 1-3.87-5.28l-.06-.14c-.75-1.93.77-3 1.6-3.56.261-.174.508-.368.74-.58a.938.938 0 0 0 .28-.74A6 6 0 0 0 13 13.19a2.723 2.723 0 0 0-1.83-.96ZM27 19.34h-2.26a1.075 1.075 0 0 0-1.06-1.06v-2.23h.02a3.315 3.315 0 0 1 3.3 3.29ZM32.3 19.34h-2.23c-.033-3.481-2.899-6.329-6.38-6.34v-2.28c4.725.005 8.61 3.895 8.61 8.62Z" style="fill:#fff;fill-rule:nonzero" transform="matrix(1.4375 0 0 1.53125 1164.09 236.548)"/>
      <path d="M37.5 19.33h-2.23c-.005-6.351-5.229-11.575-11.58-11.58V5.52c7.574.005 13.805 6.236 13.81 13.81Z" style="fill:#fff;fill-rule:nonzero" transform="matrix(1.4375 0 0 1.53125 1164.09 236.548)"/>
    </g>
  </g>
</svg>
```
After downgrading Flutter back to 2.8.1, it started displaying as expected.

I need to mention that some other SVG (which I tried during troubleshooting) displayed correctly with Flutter 2.10.0.

I observe this issue on Android and iOS.

Is something wrong with my SVG? (but it does not change between Flutter version update)
Or is there some broken change happening in the new Flutter version?

**Comment by Snowcrash5** [comment] 2022-02-06 20:24
This happens to me also

**Comment by dnfield** [comment] 2022-02-06 20:52
I'm trying to create a smaller example of this. If there are other svgs that fail to render please add them here.  @flar fyi

**Comment by Maatteogekko** [comment] 2022-02-08 09:31
With this SVG, the circular arrow does not render.

![euro_circular](https://user-images.githubusercontent.com/54111322/152955539-292adf00-528a-40c1-ad50-7f4588b13ab2.svg)
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 40 40">
    <rect width="40" height="40" fill="none" />
    <g transform="translate(8 6)">
        <path d="M18.308,10.5H6" transform="translate(-2.385 -0.346)" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" />
        <path d="M17.077,13.5H6" transform="translate(-2.385 0.346)" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" />
        <path d="M20.423,19.038A5.893,5.893,0,0,1,15.355,21.5a8.248,8.248,0,0,1-7.855-8,8.248,8.248,0,0,1,7.855-8,5.721,5.721,0,0,1,5.068,2.462" transform="translate(-2.039 -1.5)" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" />
    </g>
    <g transform="translate(-1376.513 -504.596)" opacity="0.5">
        <path d="M1399.985,542.068l3.472-3.472-3.472-3.472" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" />
        <path d="M1407.826,533.909a15.945,15.945,0,0,0,4.687-11.313h0a16,16,0,1,0-16,16h6.944" fill="none" stroke="#fff" stroke-linecap="round" stroke-width="2" />
    </g>
</svg>
```

**Comment by Riiquezz** [comment] 2022-02-09 11:55
same error here, any solution?

**Comment by deibeeed** [comment] 2022-02-11 12:14
same issue.
```
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
<g>
	<g>
		<path d="M386.689,304.403c-35.587,0-64.538,28.951-64.538,64.538s28.951,64.538,64.538,64.538
			c35.593,0,64.538-28.951,64.538-64.538S422.276,304.403,386.689,304.403z M386.689,401.21c-17.796,0-32.269-14.473-32.269-32.269
			c0-17.796,14.473-32.269,32.269-32.269c17.796,0,32.269,14.473,32.269,32.269C418.958,386.738,404.485,401.21,386.689,401.21z"/>
	</g>
</g>
<g>
	<g>
		<path d="M166.185,304.403c-35.587,0-64.538,28.951-64.538,64.538s28.951,64.538,64.538,64.538s64.538-28.951,64.538-64.538
			S201.772,304.403,166.185,304.403z M166.185,401.21c-17.796,0-32.269-14.473-32.269-32.269c0-17.796,14.473-32.269,32.269-32.269
			c17.791,0,32.269,14.473,32.269,32.269C198.454,386.738,183.981,401.21,166.185,401.21z"/>
	</g>
</g>
<g>
	<g>
		<path d="M430.15,119.675c-2.743-5.448-8.32-8.885-14.419-8.885h-84.975v32.269h75.025l43.934,87.384l28.838-14.5L430.15,119.675z"
			/>
	</g>
</g>
<g>
	<g>
		<rect x="216.202" y="353.345" width="122.084" height="32.269"/>
	</g>
</g>
<g>
	<g>
		<path d="M117.781,353.345H61.849c-8.912,0-16.134,7.223-16.134,16.134c0,8.912,7.223,16.134,16.134,16.134h55.933
			c8.912,0,16.134-7.223,16.134-16.134C133.916,360.567,126.693,353.345,117.781,353.345z"/>
	</g>
</g>
<g>
	<g>
		<path d="M508.612,254.709l-31.736-40.874c-3.049-3.937-7.755-6.239-12.741-6.239H346.891V94.655
			c0-8.912-7.223-16.134-16.134-16.134H61.849c-8.912,0-16.134,7.223-16.134,16.134s7.223,16.134,16.134,16.134h252.773v112.941
			c0,8.912,7.223,16.134,16.134,16.134h125.478l23.497,30.268v83.211h-44.639c-8.912,0-16.134,7.223-16.134,16.134
			c0,8.912,7.223,16.134,16.134,16.134h60.773c8.912,0,16.134-7.223,16.135-16.134V264.605
			C512,261.023,510.806,257.538,508.612,254.709z"/>
	</g>
</g>
<g>
	<g>
		<path d="M116.706,271.597H42.487c-8.912,0-16.134,7.223-16.134,16.134c0,8.912,7.223,16.134,16.134,16.134h74.218
			c8.912,0,16.134-7.223,16.134-16.134C132.84,278.82,125.617,271.597,116.706,271.597z"/>
	</g>
</g>
<g>
	<g>
		<path d="M153.815,208.134H16.134C7.223,208.134,0,215.357,0,224.269s7.223,16.134,16.134,16.134h137.681
			c8.912,0,16.134-7.223,16.134-16.134S162.727,208.134,153.815,208.134z"/>
	</g>
</g>
<g>
	<g>
		<path d="M180.168,144.672H42.487c-8.912,0-16.134,7.223-16.134,16.134c0,8.912,7.223,16.134,16.134,16.134h137.681
			c8.912,0,16.134-7.223,16.134-16.134C196.303,151.895,189.08,144.672,180.168,144.672z"/>
	</g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
</svg>

```
this SVG was working on pre 2.10 and now it was not. the svgs did not change as I change fultter versions.

**Comment by flar** [comment] 2022-02-11 20:56
I am able to reproduce the problem in the description running on 2.10 with flutter_svg 1.0.3. The graphic doesn't appear.

I am not able to reproduce any of the other examples provided by @Maatteogekko and @deibeeed - all 3 of those examples work just fine for me in that environment.

The problem with the first example seems to be that we get the bounds wrong (as in empty) when there are certain combinations of nested groupings with varying attributes. I'm still diagnosing where we go wrong with that.

**Comment by dnfield** [comment] 2022-02-14 04:12
Closing in favor of https://github.com/flutter/flutter/issues/98361

@Maatteogekko @deibeeed feel free to open a new issue for your SVGs if they are not fixed by this.

**Closed by dnfield** 2022-02-14 04:12 UTC
