### ISSUE TITLE
Failed to find definition for N

### ISSUE THREAD

**Issue by iBog** [dnfield/flutter_svg#333] opened 2020-04-23 12:19 UTC
path with linear gradient does not rendered with error:
════════ Exception caught by SVG ════════
The following assertion was thrown in _getDefinitionPaint:
Failed to find definition for url(#_Linear1)
This library only supports <defs> and xlink:href references that are defined ahead of their references.
════════════════════════════════
Tested svg files (exported from Figma, Affinity Designer, Inkscape)

```
<svg....>
<path d="M249.379,157.207C249.379,157.207 222.567............" style="fill:url(#_Linear1);fill-rule:nonzero;"/>
...lots of other <path>...
    <defs>
        <linearGradient id="_Linear1" x1="0" y1="0" x2="1" y2="0" gradientUnits="userSpaceOnUse" gradientTransform="matrix(29.125,64.0226,-64.0226,29.125,212.375,53.4774)">
       <stop offset="0" style="stop-color:rgb(18,56,103);stop-opacity:1"/>
       <stop offset="1" style="stop-color:rgb(19,77,150);stop-opacity:1"/>
       </linearGradient>
</defs>
</svg>
```

All vector editors created defs tag bellow path...
Moving defs prior to path  is solving problem but this is not correct, need preload <defs> before <path> in flutter_svg parser

**Comment by dnfield** [comment] 2020-04-23 14:29
The problem isn't just preloading - SVG allows for some pretty strange and inefficient defs placements, and this library doesn't support that. See more discussion at #102. This is a dupe of that issue.

**Closed by dnfield** 2020-04-23 14:29 UTC
