### ISSUE TITLE
The method 'XmlPushReader' isn't defined for the class '#lib1::SvgParser'.

### ISSUE THREAD

**Issue by philipfeldmann** [dnfield/flutter_svg#107] opened 2019-01-25 16:23 UTC
Hey there,
I basically copied from the examples, trying to pull and display an SVG from the network like so:

```
SvgPicture.network(
                'https://pub.dartlang.org/static/img/dart-logo.svg',
                semanticsLabel: 'A shark?!',
                placeholderBuilder: (BuildContext context) => new Container(
                    padding: const EdgeInsets.all(30.0),
                    child: const CircularProgressIndicator()),
              ),
```
It'll throw the following error though:
```
flutter: ══╡ EXCEPTION CAUGHT BY SVG ╞═══════════════════════════════════════════════════════════════════════
flutter: The following _CompileTimeError was thrown resolving a single-frame picture stream:
flutter: 'package:flutter_svg/parser.dart': error: line 14 pos 33:
flutter: file:///~/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.10.2/lib/parser.dart:14:33:
flutter: Error: The method 'XmlPushReader' isn't defined for the class '#lib1::SvgParser'.
flutter: Try correcting the name to the name of an existing method, or defining a method named
flutter: 'XmlPushReader'.
flutter:     return await SvgParserState(XmlPushReader(str), key).parse();
flutter:                                 ^^^^^^^^^^^^^
flutter:     return await SvgParserState(XmlPushReader(str), key).parse();
flutter:                                 ^
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #1      SvgParser.parse (package:flutter_svg/parser.dart:13:29)
flutter: #2      Svg.fromSvgString (package:flutter_svg/svg.dart:110:25)
```

SVG seems to be loaded as throwing the error takes a second, parsing however fails. Any clues why this happens?
I'm using version `0.10.2`, running on iOS.

**Comment by dnfield** [comment] 2019-01-25 16:30
Duplicate of #106 fix incoming....

**Closed by dnfield** 2019-01-25 16:30 UTC
