### ISSUE TITLE
Incorrect path formings

### ISSUE THREAD

**Issue by cuteUtya** [dnfield/flutter_svg#686] opened 2022-03-21 17:03 UTC
First - result that show package 
Second - file that cause that behaviur, i tested this SVG in last stable chrome and it look normal 

As i understand problems cause in ```<path>``` element that already supported

![Screenshot_2](https://user-images.githubusercontent.com/61709763/159311766-6a544feb-465f-4962-b784-06387a943bf8.png)
![pattern_(2)](https://user-images.githubusercontent.com/61709763/159311767-c20dfd86-1512-40a8-800f-f167e3b2a89b.svg)

**Comment by dnfield** [comment] 2022-03-21 17:09
Duplicate of #105

**Closed as completed by dnfield** 2022-03-21 17:09 UTC
