### ISSUE TITLE
Tried to download svg file using flutter_svg, encountered with below error:

### ISSUE THREAD

**Issue by ishaileshmishra** [dnfield/flutter_svg#281] opened 2020-01-28 08:29 UTC
Below log been generated and svg file not downloaded.
```
flutter: ══╡ EXCEPTION CAUGHT BY SVG 
flutter: The following StateError was thrown resolving a single-frame picture stream:
flutter: Bad state: Expected to find Drawable with id url(#use3396).
flutter: Have ids: (url(#svg548), url(#g42903), url(#rect576), url(#path570))
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      DrawableDefinitionServer.getDrawable (package:flutter_svg/src/vector_drawable.dart:577:7)
flutter: #1      _Elements.use (package:flutter_svg/src/svg/parser_state.dart:154:34)
flutter: #2      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:745:26)
flutter: <asynchronous suspension>
flutter: #3      SvgParser.parse (package:flutter_svg/parser.dart:14:60)
flutter: #4      Svg.fromSvgString (package:flutter_svg/svg.dart:110:25)
flutter: #5      Svg.fromSvgBytes (package:flutter_svg/svg.dart:93:12)
flutter: #6      Svg.svgPictureDecoder (package:flutter_svg/svg.dart:45:40)
flutter: #7      SvgPicture.svgByteDecoderOutsideViewBox.<anonymous closure> (package:flutter_svg/svg.dart:536:15)
flutter: #8      NetworkPicture._loadAsync (package:flutter_svg/src/picture_provider.dart:511:12)
flutter: <asynchronous suspension>
flutter: #9      NetworkPicture.load (package:flutter_svg/src/picture_provider.dart:497:43)
flutter: #10     PictureProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter_svg/src/picture_provider.dart:326:17)
flutter: #11     PictureCache.putIfAbsent (package:flutter_svg/src/picture_cache.dart:67:22)
flutter: #12     PictureProvider.resolve.<anonymous closure> (package:flutter_svg/src/picture_provider.dart:324:16)
flutter: #13     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
flutter: #14     PictureProvider.resolve (package:flutter_svg/src/picture_provider.dart:321:24)
flutter: #15     _SvgPictureState._resolveImage (package:flutter_svg/svg.dart:641:10)
flutter: #16     _SvgPictureState.didChangeDependencies (package:flutter_svg/svg.dart:615:5)
flutter: #17     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4376:12)
flutter: #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
flutter: #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
flutter: #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #45     _ListTileElement._mountChild (package:flutter/src/material/list_tile.dart:999:30)
flutter: #46     _ListTileElement.mount (package:flutter/src/material/list_tile.dart:1013:5)
flutter: #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #55     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
flutter: #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #60     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #61     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #64     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
flutter: #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #67     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
flutter: #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #76     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
flutter: #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #81     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #82     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
flutter: #83     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #88     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #89     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #92     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
flutter: #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #95     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
flutter: #96     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #99     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #100    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #101    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #107    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
flutter: #108    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #113    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #114    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #118    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #119    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #120    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
flutter: #121    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #122    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #125    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #126    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #127    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #129    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #131    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #132    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #133    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #134    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #135    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #136    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
flutter: #137    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #138    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #139    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #140    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #141    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #142    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #143    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #144    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #146    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #147    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #148    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
flutter: #149    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #150    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #151    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #152    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
flutter: #153    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #154    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #155    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #156    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #157    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #158    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #159    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #160    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #161    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
flutter: #162    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #163    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #164    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #165    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #166    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #167    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #168    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #169    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #170    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
flutter: #171    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #172    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #173    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #174    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #175    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #176    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
flutter: #177    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #178    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #179    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #180    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #181    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #182    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #183    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
flutter: #184    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #185    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #186    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #187    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
flutter: #188    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #189    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #190    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #191    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #192    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #193    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #194    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #195    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #196    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
flutter: #197    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #198    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #199    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #200    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #201    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #202    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #203    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #204    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #205    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
flutter: #206    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #207    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #208    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
flutter: #209    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #210    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #211    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #212    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #213    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #214    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #215    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #216    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #217    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #218    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #219    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #220    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #221    ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4617:11)
flutter: #222    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #223    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #224    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #225    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #226    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #227    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
flutter: #228    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #229    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #230    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #231    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
flutter: #232    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #233    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
flutter: #234    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #235    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
flutter: #236    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
flutter: #237    SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1288:36)
flutter: #238    SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1273:20)
flutter: #239    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2412:19)
flutter: #240    SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1266:11)
flutter: #241    RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
flutter: #242    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1823:58)
flutter: #243    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:875:15)
flutter: #244    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1823:13)
flutter: #245    RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
flutter: #246    RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:489:5)
flutter: #247    RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:195:19)
flutter: #248    RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:238:19)
flutter: #249    RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
flutter: #250    RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:134:11)
flutter: #251    RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:373:11)
flutter: #252    RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
flutter: #253    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:410:13)
flutter: #254    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1367:12)
flutter: #255    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1285:20)
flutter: #256    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
flutter: #257    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
flutter: #258    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344:19)
flutter: #259    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
flutter: #260    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
flutter: #261    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
flutter: #262    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
flutter: #263    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
flutter: #267    _invoke (dart:ui/hooks.dart:259:10)
flutter: #268    _drawFrame (dart:ui/hooks.dart:217:3)
flutter: (elided 3 frames from package dart:async)
flutter:
flutter: Picture provider: NetworkPicture("https://restcountries.eu/data/iot.svg", headers: null,
flutter:   colorFilter: null)
flutter: Picture key: NetworkPicture("https://restcountries.eu/data/iot.svg", headers: null, colorFilter:
flutter:   null):
```

**Comment by dnfield** [comment] 2020-01-28 08:32
Duplicate of #102

**Closed by dnfield** 2020-01-28 08:32 UTC
