### ISSUE TITLE
SVG Shadow is not Showing in Android & IOS 

### ISSUE THREAD

**Issue by rupamking1** [dnfield/flutter_svg#467] opened 2020-12-18 15:12 UTC
SVG Shadow is not Showing in Android & IOS,
You can use Android & IOS native packages for solve shadow bug.
Please implement this anyway we need show shadow in App.

**Comment by dnfield** [comment] 2020-12-18 15:33
Dupe of #53

**Closed by dnfield** 2020-12-18 15:33 UTC

**Comment by rupamking1** [comment] 2020-12-18 15:36
I understood this issue is duplicate but please tell me when you make shadow feature in svg plugin.

**Comment by dnfield** [comment] 2020-12-18 15:38
One work around is to draw the shadow in flutter instead.

**Comment by aytunch** [comment] 2021-08-04 14:30
> One work around is to draw the shadow in flutter instead.

@dnfield Could you please share a code snippet which does the faking in Flutter?

**Comment by ayoubm** [comment] 2022-01-24 23:45
Or use this widget to wrap your SvgPicture asset: https://pub.dev/packages/simple_shadow ! Works perfectly fine !

**Comment by furkanksl** [comment] 2022-10-19 10:19
@ayoubm 

My UI appreciate you. 😄

**Comment by Munsif-Ali** [comment] 2025-05-04 08:51
I used `simple_shadow` it is working fine with some Svgs but it is not working when hollow svg are used. I just published a package which handle this case and also work with Icons, Images, and text
[Shadex](https://pub.dev/packages/shadex)
use it like this 
```dart
Shadex(
  child: SvgPicture.asset('assets/icons/star.svg'),
  shadowColor: Colors.black45,
  shadowBlurRadius: 6.0,
  shadowOffset: Offset(4, 4),
)
```
