### ISSUE TITLE
Cannot display gradient svg icon.

### ISSUE THREAD

**Issue by kaxp** [dnfield/flutter_svg#189] opened 2019-07-04 06:42 UTC
Hi, I'm trying to add a gradient logo on the splash screen using flutter_svg plugin, but it is not showing the gradient colour instead it just displays the logo in black colour. So what should I do to display the gradient logo. Thanks in advance

**Comment by dnfield** [comment] 2019-07-04 14:05
Do you have a SVG that reproduces the issue?

**Comment by kaxp** [comment] 2019-07-05 05:50
@dnfield below is the svg which is not displaying properly.
 <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 600 377.7"><defs><style>.cls-1,.cls-2,.cls-3{opacity:0.4;}.cls-1{fill:url(#linear-gradient);}.cls-2{fill:url(#linear-gradient-2);}.cls-3{fill:url(#linear-gradient-3);}.cls-4{fill:#fff;}.cls-5,.cls-6{opacity:0.25;}.cls-5{fill:url(#linear-gradient-4);}.cls-6{fill:url(#linear-gradient-5);}</style><linearGradient id="linear-gradient" x1="358.87" y1="291.73" x2="180.24" y2="21.46" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#3affda"/><stop offset="0.08" stop-color="#41f6db" stop-opacity="0.99"/><stop offset="0.22" stop-color="#54dedf" stop-opacity="0.97"/><stop offset="0.4" stop-color="#73b6e5" stop-opacity="0.94"/><stop offset="0.6" stop-color="#9d7fed" stop-opacity="0.9"/><stop offset="0.83" stop-color="#d339f7" stop-opacity="0.84"/><stop offset="1" stop-color="#f0f" stop-opacity="0.8"/></linearGradient><linearGradient id="linear-gradient-2" x1="240.79" y1="291.71" x2="419.41" y2="22.22" xlink:href="#linear-gradient"/><linearGradient id="linear-gradient-3" x1="300.01" y1="271.97" x2="300.01" y2="0" xlink:href="#linear-gradient"/><linearGradient id="linear-gradient-4" x1="435.98" y1="203.03" x2="205.4" y2="34.56" gradientUnits="userSpaceOnUse"><stop offset="0.5" stop-color="#fff" stop-opacity="0"/><stop offset="0.61" stop-color="#fff" stop-opacity="0.28"/><stop offset="0.71" stop-color="#fff" stop-opacity="0.54"/><stop offset="0.81" stop-color="#fff" stop-opacity="0.74"/><stop offset="0.89" stop-color="#fff" stop-opacity="0.88"/><stop offset="0.96" stop-color="#fff" stop-opacity="0.97"/><stop offset="1" stop-color="#fff"/></linearGradient><linearGradient id="linear-gradient-5" x1="163.14" y1="203.49" x2="394.58" y2="34.96" xlink:href="#linear-gradient-4"/></defs><title>landing page logoAsset 2</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><path class="cls-1" d="M299.93,0,157.39,103.67,211.94,272a134.82,134.82,0,0,1,176.13,0Z"/><path class="cls-2" d="M299.93,0l-88,272a134.82,134.82,0,0,1,176.13,0l54.51-168.32Z"/><path class="cls-3" d="M300,0l-88,64V272a134.82,134.82,0,0,1,176.13,0V64Z"/><path class="cls-4" d="M300,239.23A134.46,134.46,0,0,0,211.94,272C231.5,257.83,260.1,242,300,241.88c39.91.16,68.52,16,88.07,30.08A134.45,134.45,0,0,0,300,239.23Z"/><path class="cls-5" d="M157.38,103.65,370,258.79A126.93,126.93,0,0,1,388.07,272l54.5-168.3Z"/><path class="cls-6" d="M442.62,103.64,230,258.78A127,127,0,0,0,211.93,272l-54.5-168.29Z"/><path class="cls-4" d="M25.57,344.78l-1.7,7.16a21.14,21.14,0,0,0-8.72-2.09c-3.11,0-5.7.92-5.6,2.87.1,2.19,3.8,2.34,8.33,3.4,5.51,1.37,10.37,3.6,10.43,10.09,0,7.69-6.77,11.3-14.46,11.34A30.06,30.06,0,0,1,0,374l2.44-7.16A22.38,22.38,0,0,0,13.25,370c3.85,0,6.08-1.42,6.14-3.21.05-2.58-4.48-2.49-9-3.66-5.26-1.31-9.69-4.09-9.74-10-.09-7.74,7.11-10.76,13.88-10.76A26.94,26.94,0,0,1,25.57,344.78Z"/><path class="cls-4" d="M68.89,350.38v26.54H60.18V350.38h-11v-7.54H79.9v7.54Z"/><path class="cls-4" d="M171.94,368.2c-.54,0-1.07.1-1.56.1-1.6,0-3.7,0-4.58,0v8.62h-8.86V342.84c4.24-.1,8.37-.2,12.47-.2,9.88.06,15.87,5.12,15.87,12.67a11.73,11.73,0,0,1-5.16,9.92L186,376.92h-10Zm4.48-12.81c0-3.36-3.12-5-6.52-5.2a36.76,36.76,0,0,0-4.14,0V360.8a35.26,35.26,0,0,0,4.43-.1C174.42,360.31,176.42,358.27,176.42,355.39Z"/><path class="cls-4" d="M275.49,344.54l-2.77,7.06a15.51,15.51,0,0,0-7.74-2c-5.59.1-11,3.51-11,10.38s5.36,10.13,11,10.13a14.61,14.61,0,0,0,7.69-2.2l3,7a23.59,23.59,0,0,1-11.05,2.83c-10,0-19.63-6.19-19.63-17.67,0-10.81,8.57-17.87,19.19-18A26.52,26.52,0,0,1,275.49,344.54Z"/><path class="cls-4" d="M300.32,376.92V342.84H309v34.08Z"/><path class="cls-4" d="M360.12,376.92l-15.68-20.64v20.64h-8.77V342.84h8.72l15.44,20.74V342.84h8.76v34.08Z"/><path class="cls-4" d="M404.25,350.38v6h12.66v6.87H404.25v6.13h17.82v7.55H395.39V342.84H421v7.54Z"/><path class="cls-4" d="M479.33,376.92v-20.7l-11.79,15.39L456,356.17v20.74h-8.82V342.84h8.33l12,16.06,12.27-16.06h8.47v34.08Z"/><path class="cls-4" d="M597.27,344.78l-1.7,7.16a21.1,21.1,0,0,0-8.72-2.09c-3.12,0-5.7.92-5.6,2.87.1,2.19,3.8,2.34,8.33,3.4,5.51,1.37,10.37,3.6,10.42,10.09.05,7.69-6.77,11.3-14.46,11.34a30.08,30.08,0,0,1-13.83-3.5l2.43-7.16A22.36,22.36,0,0,0,585,370c3.85,0,6.09-1.42,6.14-3.21,0-2.58-4.48-2.49-9-3.66-5.26-1.31-9.69-4.09-9.74-10-.09-7.74,7.11-10.76,13.88-10.76A26.88,26.88,0,0,1,597.27,344.78Z"/><polygon class="cls-4" points="110.17 363.04 110.18 363.04 114.69 351.4 110.17 363.04"/><polygon class="cls-4" points="119.27 363.04 114.69 351.4 119.27 363.04 119.27 363.04"/><polyline class="cls-4" points="114.69 351.4 119.27 363.04 119.27 363.04 124.72 376.92 133.93 376.92 119.13 342.84 110.26 342.84 95.56 376.92 104.81 376.92 110.18 363.04"/><polygon class="cls-4" points="525.96 363.04 525.98 363.04 530.49 351.4 525.96 363.04"/><polygon class="cls-4" points="535.07 363.04 530.49 351.4 535.06 363.04 535.07 363.04"/><polyline class="cls-4" points="530.49 351.4 535.07 363.04 535.06 363.04 540.52 376.92 549.72 376.92 534.92 342.84 526.06 342.84 511.35 376.92 520.6 376.92 525.98 363.04"/></g></g></svg>

**Comment by dnfield** [comment] 2019-07-05 06:02
The style attribute is not supported - duplicate of #105

**Closed by dnfield** 2019-07-05 06:02 UTC
