### ISSUE TITLE
AssetBundlePictureKey Exception, Colorless svg image appears

### ISSUE THREAD

**Issue by II11II** [dnfield/flutter_svg#512] opened 2021-03-11 08:29 UTC
Expected:
![image](https://user-images.githubusercontent.com/45257709/110757870-acf95680-826d-11eb-8ed2-5aa61f06d8a4.png)

Output:
![image](https://user-images.githubusercontent.com/45257709/110757802-9d7a0d80-826d-11eb-8d07-83d35d794cc2.png)

Log: 
```
Exception caught by SVG ═══════════════════════════════════════════════
The following assertion was thrown while parsing AssetBundlePictureKey(bundle: PlatformAssetBundle#76c04(), name: "assets/images/logo.svg", colorFilter: null) in _getDefinitionPaint:
Failed to find definition for url(#paint0_linear)

This library only supports <defs> and xlink:href references that are defined ahead of their references.

This error can be caused when the desired definition is defined after the element referring to it (e.g. at the end of the file), or defined in another file.

This error is treated as non-fatal, but your SVG file will likely not render as intended
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by SVG ═══════════════════════════════════════════════
Failed to find definition for url(#paint1_linear)

════════ Exception caught by SVG ═══════════════════════════════════════════════
Failed to find definition for url(#paint2_linear)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by SVG ═══════════════════════════════════════════════
Failed to find definition for url(#paint3_linear)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by SVG ═══════════════════════════════════════════════
Failed to find definition for url(#paint4_linear)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by SVG ═══════════════════════════════════════════════
Failed to find definition for url(#paint5_linear)
```

**Comment by dnfield** [comment] 2021-03-11 08:53
likely dupe of #102 

Please provide the SVG source if you think that's not the case.

**Closed by dnfield** 2021-03-11 08:53 UTC
