### ISSUE TITLE
Invalid double 1pt 

### ISSUE THREAD

**Issue by leecasey** [dnfield/flutter_svg#746] opened 2022-08-05 17:50 UTC
Hi, not sure whats happened but this was working fine for me. I am rendering some svg flags. Some of them show and some don't and throw an exception. 

Exception caught by SVG
Invalid double
1pt

I'm not using pt's anywhere. Is there a fix for this? I've tried rolling back versions but same problem now.

**Comment by dnfield** [comment] 2022-08-05 18:00
Duplicate of #743

**Closed by dnfield** 2022-08-05 18:00 UTC
