### ISSUE TITLE
SvgPicture.assets and SvgPicture.string both not rendering pattern tag image - flutter

### ISSUE THREAD

**Issue by WasimAndroidIvan** [dnfield/flutter_svg#294] opened 2020-02-13 12:40 UTC
This is the complete examplesvg Code:
[Untitled document.txt](https://github.com/dnfield/flutter_svg/files/4198362/Untitled.document.txt)

Note:
1. Already cleaned the examplesvg using this website https://jakearchibald.github.io/svgomg/. 
2. SvgPicture.assets or SvgPicture.string both are not rendering the pattern image.

Please kindly look into the issue. kindly point out where I am doing wrong.

**Comment by dnfield** [comment] 2020-02-13 14:53
Dupe of #289

**Closed by dnfield** 2020-02-13 14:53 UTC
