### ISSUE TITLE
_handleImageChanged: setState() or markNeedsBuild() called when widget tree was locked

### ISSUE THREAD

**Issue by rupinderjeet** [dnfield/flutter_svg#779] opened 2022-09-27 05:39 UTC
Hi, I am using your SVG library to display filter-like chip items in a horizontal list using `AutomaticAnimatedListView` from `great_list_view` library. An exception is thrown when I try to remove an item from this list. Since, the exception stack trace primarily points to SVG library, I am assuming that the issue is with this library. But, I am not sure, so please let me know if I should add an issue for the other library.

To reproduce the issue, I load this list with with some items. When I remove an item, `provider` notifies the change using `Selector` widget, which refreshes `AutomaticAnimatedListView` with a new `List<FilterChipItem>`. I have added the code below the following exception trace:
```
======== Exception caught by SVG ===================================================================
The following assertion was thrown by a synchronously-called image listener:
setState() or markNeedsBuild() called when widget tree was locked.

This SvgPicture widget cannot be marked as needing to build because the framework is locked.
The widget on which setState() or markNeedsBuild() was called was: SvgPicture
  dirty
  dependencies: [Directionality, _LocalizationsScope-[GlobalKey#98569], DefaultTextStyle]
  state: _SvgPictureState#cf7c8(lifecycle state: initialized, stream: PictureStream#b5d7a(OneFramePictureStreamCompleter#b4348, Instance of 'PictureInfo', 6 listeners, cached))
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4481:9)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4491:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1129:15)
#3      _SvgPictureState._handleImageChanged (package:flutter_svg/svg.dart:814:5)
#4      PictureStreamCompleter.addListener (package:flutter_svg/src/picture_stream.dart:297:17)
#5      PictureStream.addListener (package:flutter_svg/src/picture_stream.dart:204:26)
#6      _SvgPictureState._listenToStream (package:flutter_svg/svg.dart:843:21)
#7      _SvgPictureState.didChangeDependencies (package:flutter_svg/svg.dart:752:5)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4963:11)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
...     Normal element mounting (64 frames)
#73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#74     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#75     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (22 frames)
#97     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#98     Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#99     AnimatedSliverMultiBoxAdaptorElement.updateChild (package:great_list_view/src/core/child_manager.dart:336:28)
#100    AnimatedSliverMultiBoxAdaptorElement._disposableElement.<anonymous closure> (package:great_list_view/src/core/child_manager.dart:507:36)
#101    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2516:15)
#102    AnimatedSliverMultiBoxAdaptorElement._disposableElement (package:great_list_view/src/core/child_manager.dart:505:12)
#103    AnimatedRenderSliverList.measureItem (package:great_list_view/src/core/sliver_list.dart:652:18)
#104    AnimatedRenderSliverList._measureItems.<anonymous closure> (package:great_list_view/src/core/sliver_list.dart:639:17)
(elided 12 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
====================================================================================================
```

Here's my `FilterChipLayout` widget state (some code simplified):
```
class _FilterChipLayoutState extends State<FilterChipLayout> {
  late AnimatedListController _listController;
  late ScrollController _scrollController;

  @override
  void initState() {
    super.initState();
    _listController = widget.listController ?? AnimatedListController();
    _scrollController = widget.scrollController ?? ScrollController();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
        height: 48,
        margin: widget.margin,
        child: AutomaticAnimatedListView<FilterChipItem>(
          list: widget.items,
          physics: const BouncingScrollPhysics(),
          scrollDirection: Axis.horizontal,
          padding: EdgeInsets.symmetric(horizontal: 8),
          comparator: AnimatedListDiffListComparator<FilterChipItem>(
              sameItem: (a, b) => a.text == b.text,
              sameContent: (a, b) => a.text == b.text),
          itemBuilder: (context, item, data) {
            return FilterChipWidget(
              title: item.text,
              icon: SvgPicture.asset(randomSvg(), color: Colors.black, width: 16, height: 16),
              margin: EdgeInsets.only(right: 8),
              onIconTap: item.action,
            );
          },
          listController: _listController,
          scrollController: _scrollController,
        ));
  }
}
```

Here's my `FilterChipItem` (for completeness):
```
class FilterChipItem {
  FilterChipItem({
    required this.text,
    required this.action,
  });

  final String text;
  final VoidCallback action;
}
```

Here's how I use `FilterChipLayout`:
```
Selector<SongsModel, List<SongGenre>?>(
  selector: (_, model) => model.selectedGenres,
  builder: (_, selectedGenres, __) {
    if (selectedGenres == null || selectedGenres.isEmpty) {
      return SizedBox();
    }

    return FilterChipLayout(
        margin: EdgeInsets.only(top: 8),
        items: selectedGenres.map(_genreToFilterChipItem).toList(),
        onRemoveTap: _songsModel.removeSelectedGenre);
  })
)
```

I don't know if above code will help you in locating the issue, but please let me know if I missed something.

**Comment by rupinderjeet** [comment] 2022-09-27 05:43
```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.1 21C52 darwin-x64, locale en-GB)
flutter_svg: 1.1.5 (issue exists in 1.0.3 as well)
great_list_view: https://github.com/rupinderjeet/great_list_view/tree/fix/widgetsbindinginstance (fork for some warnings)
```

**Comment by dnfield** [comment] 2022-09-27 16:02
I'm guessing I need a mounted check there.

**Comment by dnfield** [comment] 2022-09-27 16:04
Do you have a small application that replicates this? I can see one spot where I could make a change that migh thelp, but I'd like to test it.

**Comment by rupinderjeet** [comment] 2022-09-29 11:27
@dnfield Sure, I will prepare a sample and share with you.

**Comment by rupinderjeet** [comment] 2022-09-29 12:52
@dnfield Here's a sample for reproducing the issue:

https://github.com/rupinderjeet/issue_779_flutter_svg

Steps: either tap on "Load" button and try to remove one of the items.
Observe: Console logs

**Comment by dnfield** [comment] 2022-09-29 16:20
I think this is a bug in https://github.com/rupinderjeet/great_list_view/blob/99c47142a13aa493608ebb59fd1693c8173decba/lib/src/core/child_manager.dart#L505

I don't believe this is a correct usage of `lockState`.

@goderbauer interested in what you think about this. `flutter_svg` is calling `setState` in a callback that's fired immediately from `didChangeDependencies`. However, when `didChangeDependencies` is called, the tree is locked because the `great_list_view` package has marked it as locked. I think that is a mistake in great_list_view, but there's no way for a caller of `setState` to actually check if the tree is locked. If I'm right then we don't need a way to check that, but the caller to `lockState` actually made a mistake here (lockState is documented as being intended for preventing setState calls when an element is not yet mounted or when it is being unmounted/disposed).

**Comment by goderbauer** [comment] 2022-09-29 16:39
calling setState from didChangeDependencies is totally fine. 

This `lockState` in great_list_view does look out of place. When briefly looking at it, I couldn't find the call side for `_disposableElement` - so it is not clear to me why they are doing this. A wild guess may be that they may want to use `invokeLayoutCallback` and/or `buildScope` instead if this implements some version of a LayoutBuilder.

**Comment by rupinderjeet** [comment] 2022-10-03 04:46
Thank you for these observations. I will try to look into and follow the code of that library to understand it better in following days. Even though both libraries are functioning properly with/without this exception, I still want to find a solution. It seems that the most reasonable thing to do is to test the library after removing `lockState` wrapper (possible search for other similar uses as well). If this fails, I will try contacting the author.

If there is nothing that you may need to do to fix or improve this scenario, please feel free to close this ticket.

**Closed** 2022-10-03 05:08 UTC

**Comment by zeeshan0080** [comment] 2023-11-08 11:58
> great_list_view

The problem is in your itemBuilder, before returning FilterChipWidget() you have to add a check while it compares items.
Like this:
itemBuilder: (context, item, data) => data.measuring
                    ? const SizedBox.shrink() //you can show loader here if you want
                    : FilterChipWidget()

**Comment by LIsmooth** [comment] 2024-02-22 15:29
I got this error, and solved in @zeeshan0080 's way, many thanks!
