### ISSUE TITLE
SVG Image Error

### ISSUE THREAD

**Issue by reya276** [dnfield/flutter_svg#564] opened 2021-05-28 03:00 UTC
I keep getting the error beow: I created the image using inkscape.
```
I/flutter ( 9076): unhandled element sodipodi:namedview; Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#a4718(), name: "assets/login_app.svg", colorFilter: null)
I/flutter ( 9076): unhandled element metadata; Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#a4718(), name: "assets/login_app.svg", colorFilter: null)

======== Exception caught by SVG ===================================================================
The following StateError was thrown resolving a single-frame picture stream:
Bad state: Expected to find Drawable with id none.
Have ids: (url(#svg348), url(#layer1), url(#g9656), url(#g2012))

When the exception was thrown, this was the stack: 
#0      DrawableDefinitionServer.getDrawable (package:flutter_svg/src/vector_drawable.dart:568:7)
#1      parseMask (package:flutter_svg/src/svg/xml_parsers.dart:363:24)
#2      parseStyle (package:flutter_svg/src/svg/xml_parsers.dart:436:11)
#3      SvgParserState.addShape (package:flutter_svg/src/svg/parser_state.dart:878:7)
#4      SvgParserState.startElement (package:flutter_svg/src/svg/parser_state.dart:902:12)
...
Picture provider: ExactAssetPicture(name: "assets/login_app.svg", bundle: null, colorFilter: null)
Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#a4718(), name: "assets/login_app.svg", colorFilter: null)
====================================================================================================
```

**Comment by MattisBrizard** [comment] 2021-06-17 15:30
Hi @reya276, I also have the error, did you find a way to handle this issue ?

**Comment by hakimLyon** [comment] 2022-02-26 00:32
return to `flutter_svg: ^0.22.0` or `flutter_svg: ^0.23.0 `

**Comment by dnfield** [comment] 2022-02-28 22:00
I don't know why I missed this issue back when it was posted, sorry.  Can you please share the SVG? It looks like something wrong is happening with the def parsing here.

This doesn't quite look like #102 but it may be related.

**Comment by dnfield** [comment] 2022-02-28 22:01
Going to close this, but if you're able to share the SVG and it's not a duplicate of #102 I will re-open.

**Closed by dnfield** 2022-02-28 22:01 UTC

**Comment by martinGele** [comment] 2023-01-08 15:20
There is a parsing error, just move the `<defs> </defs>` tag on top of the SVG file, just below the `<svg>` tag
