### ISSUE TITLE
Ignore title and desc tags

### ISSUE THREAD

**Issue by ueman** [dnfield/flutter_svg#203] opened 2019-07-30 08:42 UTC
Currently every [title](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title) and [desc](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/desc) tag prints an error message (`unhandled element title`) to the console. It should be ignored as it adds nothing to the graphics. 

Another idea would be to use those tags as semantics label.

**Comment by dnfield** [comment] 2019-07-30 15:51
It should only be printing that out for the first encountered element.  It'd probably be fine to ignore those at this point though, they'll never end up being used.

At one point I thought it would be good to use them for semantics, the problem is that it would only rarely work out correctly.  For example, an arrow icon that had a title "up arrow", but was actually rotated 90 degrees, or other similar icons where the title wouldn't make sense in context...

**Comment by dnfield** [comment] 2019-08-09 19:51
I'm going to exclude these by default. I have no plans to incorporate them.  Will be fixed in the next commit to master shortly.

**Closed by dnfield** 2019-08-09 19:51 UTC
