### ISSUE TITLE
Paths with more than 29 instructions do not render

### ISSUE THREAD

**Issue by andreaslillebo** [dnfield/flutter_svg#254] opened 2019-11-21 05:48 UTC
First of all, thank you for this awesome library. It's really good to be able to use SVG instead of including different versions of images to support an ever growing range of screens with different pixel densities.

**Summary:**
Paths with 29 instructions render as expected. Paths with 30 or more instructions do not render at all.

**Workaround:**
Downgrade to latest stable Flutter release (currently 1.9.1+hotfix.6).

**Details:**
The following SVG (path with 29 instructions) renders as expected:
````svg
<svg xmlns="http://www.w3.org/2000/svg" height="150px" width="150px" viewBox="0 0 150 150">
  <path fill="red" d="m0,0 h5 v5 h5 v5 h5 v5 h5 v5 h5 v5 h5 v5 h5 v5 h5 v5 h5 v5 h5 v5 h5 v5 h5 v5 h5 v5 h5 v5"/>
</svg>
````
Download:
[example_working.svg.zip](https://github.com/dnfield/flutter_svg/files/3872972/example_working.svg.zip)

Rendered in Chrome:
<img width="81" alt="working-screenshot" src="https://user-images.githubusercontent.com/24457101/69307023-c2a7ce80-0c6c-11ea-9b35-34c167e1f8e8.png">

The following SVG (path with 30 instructions) do not render:
````svg
<svg xmlns="http://www.w3.org/2000/svg" height="150px" width="150px" viewBox="0 0 150 150">
  <path fill="red" d="m0,0 h5 v5 h5 v5 h5 v5 h5 v5 h5 v5 h5 v5 h5 v5 h5 v5 h5 v5 h5 v5 h5 v5 h5 v5 h5 v5 h5 v5 h5"/>
</svg>
````
Download:
[example_broken.svg.zip](https://github.com/dnfield/flutter_svg/files/3872974/example_broken.svg.zip)

Rendered in Chrome:
<img width="77" alt="broken-screenshot" src="https://user-images.githubusercontent.com/24457101/69307093-fb47a800-0c6c-11ea-879c-13533ea5ced5.png">

-----

The Flutter debug console doesn't print any errors. The Dart DevTools show a similar tree for both the working and broken SVG.

-----

**Technical info:**
- Flutter: 1.12.4
- Dart: 2.7.0
- flutter_svg: 0.15.0

**Comment by andreaslillebo** [comment] 2019-11-21 08:15
This appears to not be a problem on the stable version of Flutter. This might not be an issue with this library.

Also I noticed that some of the test images don't render correctly on Flutter 1.12.4 either, e.g.:
https://github.com/dnfield/flutter_svg/blob/7d374d7107561cbd906d7c0ca26fef02cc01e7c8/example/assets/wikimedia/Ghostscript_Tiger.svg

**Comment by dnfield** [comment] 2019-11-21 08:20
There are definitely test images with paths that have more than 30 instructions.

I believe this issue is probably resolved on master - it's very likely a Skia issue.  It might be good to know exactly where it was introduced (and fixed) - we could add a test to the engine for it pretty easily.

**Comment by dnfield** [comment] 2019-12-09 18:18
Closing this as I'm not able to reproduce it.

**Closed by dnfield** 2019-12-09 18:18 UTC
