### ISSUE TITLE
SVGs sometimes not appearing

### ISSUE THREAD

**Issue by kbokarius** [dnfield/flutter_svg#374] opened 2020-07-01 21:10 UTC
I'm using this library with a simple use case with the following code:

```
SvgPicture.asset(
 assetLocation,
 height: 88
)
```

Most of the time the images show up as expected, however, sometimes they do not appear and I see the following errors:

```
flutter: unhandled element metadata; Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#787ab(), name: "assets/logo/xxx.svg", colorFilter: null)
flutter: unhandled element sodipodi:namedview; Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#787ab(), name: "assets/logo/xxx.svg", colorFilter: null)
```

**Comment by dnfield** [comment] 2020-07-01 22:47
Those errors are probably safe to ignore - those are tags/attributes that Inkscape adds to SVGs that shouldn't be needed for rendering (but are used by inkscape).  You can run a tool like `svgcleaner` on the SVG to get rid of them.

It'd be important to know which ones do not show up, for example a sample SVG that fails to render. It'd also be good to check that `SvgPicture.string` fails to render it, to rule out asset related failures.

**Comment by kbokarius** [comment] 2020-07-01 22:49
Gotcha, I'll try svgcleaner. After some more testing, it looks like the SVGs not showing up only happens in the iOS simulator when debugging with VSCode, we have yet to see it on a real device. The issue will either happen/go away after a hot reload. We'll dig deeper if we can reproduce on a real device, thank you!

**Comment by dnfield** [comment] 2020-07-31 17:42
I'm going to close this as I'm pretty sure it's not a bug in Flutter SVG - please feel free to comment if you've uncovered more details that indicate it is.

**Closed by dnfield** 2020-07-31 17:42 UTC
