### ISSUE TITLE
SVG Does not render properly on screen change.

### ISSUE THREAD

**Issue by pgfepale** [dnfield/flutter_svg#151] opened 2019-04-09 10:49 UTC
at first time load work fine:

![ok](https://user-images.githubusercontent.com/4177392/55794387-bf4b4280-5ae2-11e9-821f-361839253781.png)

But when we switch screen it show render problem as:
![error](https://user-images.githubusercontent.com/4177392/55794455-e6097900-5ae2-11e9-9555-2cc04a38b532.png)

Reference:
1. Work fine for iOs
2. Issue only for android devices [Even on emulator works fine] 
3. tried on deferent android devices having same problem
4. when we switch screen by click

**Comment by pgfepale** [comment] 2019-04-09 15:44
> This looks like a known bug for several versions of flutter. What version of flutter are you using?

The latest one 1.3.8

**Comment by dnfield** [comment] 2019-04-09 17:03
Unfortunately that version has a bug in path rendering.  If you try the latest beta it should work.

**Comment by dnfield** [comment] 2019-04-11 07:57
I'm going to close this for now, as it's a duplicate of #115 - but please feel free to reopen if this reproduces on Flutter dev or master.

**Closed by dnfield** 2019-04-11 07:57 UTC
